### PR TITLE
fix: xudrpc GetBalanceResponse json_name

### PR DESCRIPTION
**Pull request by reliveyy**
This PR fixes the wrong balances `json_name` which will affect Golang gRPC JSON results. See https://github.com/ExchangeUnion/xud-docker/pull/726#issuecomment-695806679

I followed the instructions in proto/README.md but I don't know why simple json_name change caused 470 lines modification in xudrpc.pb.go. Is it alright?

### CODE REVIEW

**Review by raladev — APPROVED** [review]

**Review by michael1011 — DISMISSED** [review]

**Review by sangaman — APPROVED** [review]
Thanks for catching this.

**Comment by sangaman** [comment]
The commits should be signed before they can be merged, can you do that and update the PR @reliveyy ?

**Comment by erkarl** [comment]
Looks like there's no also a merge conflict. Could you rebase this against master and regenerate the protos?

**Comment by reliveyy** [comment]
> Looks like there's no also a merge conflict. Could you rebase this against master and regenerate the protos?

@erkarl Resolved.

**Review by erkarl — APPROVED** [review]

**Pull request merged**
