### PR TITLE
add initial fee control. Allow a up to 3% fee

### PR DESCRIPTION
**Pull request by offerm**

### CODE REVIEW

**Comment by offerm** [comment]
This is needed to handle https://github.com/ExchangeUnion/xud-simnet/issues/34

I suggest to accept it as is and create a new issue for having the max fee from  configuration file.

**Comment by kilrau** [comment]
I think the change to 0.03 somehow didn't go through.

**Comment by erkarl** [comment]
No need to update `package-lock.json` within this PR.

**Comment by kilrau** [comment]
> I can make a followup to this to replace the `MAXFEE` variable with a configurable option, but this is fine as a first step. Thanks.

Covered in https://github.com/ExchangeUnion/xud/issues/915 :thumbsup:

**Pull request merged**
