### PR TITLE
test(sim): maker lnd to crash before order settlement

### PR DESCRIPTION
**Pull request by LePremierHomme**
Closing https://github.com/ExchangeUnion/xud/issues/1126.

This test relies on this commit to the `instability` custom-xud branch: https://github.com/ExchangeUnion/xud/commit/34a73540a48f4428152f7b948e42b4cf4c49637a

It doesn’t run on travis yet, and in order to test it locally, one must to disable the other instability tests, because they are currently failing.

### CODE REVIEW

**Comment by LePremierHomme** [comment]
The failing test is not the new one, but rather the one that was fixed here: https://github.com/ExchangeUnion/xud/pull/1486

You should disable it in the meanwhile for testing the new one.

**Comment by sangaman** [comment]
> The failing test is not the new one, but rather the one that was fixed here: #1486
> 
> You should disable it in the meanwhile for testing the new one.

Ahh yes sorry my mistake, I should have recognized that.

**Comment by sangaman** [comment]
I rebased this branch onto master so it would include the fix from #1486, and rebuilt everything, but now the test is hanging for me on the newly added test:

```
=== RUN   TestInstability
2020/04/24 03:38:51 xud: creating network
2020/04/24 03:38:55 ltcd: launching node...
2020/04/24 03:38:57 ltcd: 200 blocks generated
2020/04/24 03:38:57 lnd-ltc: launching network...
2020/04/24 03:39:06 btcd: launching node...
2020/04/24 03:39:07 btcd: 200 blocks generated
2020/04/24 03:39:07 lnd-btc: launching network...
2020/04/24 03:39:16 xud: launching network...
2020/04/24 03:39:18 Running 4 instability tests
=== RUN   TestInstability/network_initialization
=== RUN   TestInstability/maker_crashed_after_send_payment
2020/04/24 03:39:19 custom xud not found at /custom-xud-vol/instability, installing...
2020/04/24 03:40:05 custom xud installation finished
=== RUN   TestInstability/maker_crashed_after_send_payment_with_delayed_settlement
2020/04/24 03:40:11 custom xud found at /custom-xud-vol/instability
2020/04/24 03:40:12 custom xud found at /custom-xud-vol/instability
=== RUN   TestInstability/maker_lnd_crashed_before_order_settlement
2020/04/24 03:40:27 custom xud found at /custom-xud-vol/instability
```

**Comment by LePremierHomme** [comment]
I need to see the golang panic error msg, but it looks to me like an instability in the test infra (I think I saw this once). Please try to run it a few times, and it it happens consistently, paste here the panic error msg.

**Comment by LePremierHomme** [comment]
Rebasing wasn't enough - another fix was required. 

Each test setting a custom xud on a specific actor must be followed by a test which does the same, and thus override the previous one. 
The test `maker_crashed_after_send_payment_with_delayed_settlement` set a custom xud for both Alice and Bob, unlike the others, which set only for Alice. That's why it must be the last test in the array. 
If we want to avoid this requirement, we'll need to re-set the canonical xud after every test, which I rather not do.

Please try run it again.

**Comment by sangaman** [comment]
> Rebasing wasn't enough - another fix was required.
> 
> Each test setting a custom xud on a specific actor must be followed by a test which does the same, and thus override the previous one.
> The test `maker_crashed_after_send_payment_with_delayed_settlement` set a custom xud for both Alice and Bob, unlike the others, which set only for Alice. That's why it must be the last test in the array.
> If we want to avoid this requirement, we'll need to re-set the canonical xud after every test, which I rather not do.
> 
> Please try run it again.

Sorry for the delay, with rebasing this branch onto master and then running `npm run test:sim:clean`, `npm run test:sim:build:test`, and `npm run test:sim:run:instability` fails with this:

```
=== RUN   TestInstability/maker_crashed_after_send_payment
2020/04/30 19:21:26 custom xud found at /custom-xud-vol/instability
2020/04/30 19:21:29 lnd-btc: network harness teared down
2020/04/30 19:21:29 btcd: harness teared down
2020/04/30 19:21:29 lnd-ltc: network harness teared down
2020/04/30 19:21:29 ltcd: harness teared down
2020/04/30 19:21:29 xud network harness teared down
--- FAIL: TestInstability (34.20s)
    --- PASS: TestInstability/network_initialization (0.31s)
    --- FAIL: TestInstability/maker_crashed_after_send_payment (3.68s)
        actions.go:98: 
            	Error Trace:	actions.go:98
            	            				tests-instability.go:43
            	            				harnessTest.go:95
            	            				xud_test.go:160
            	Error:      	Received unexpected error:
            	            	rpc error: code = Unknown desc = Peer 0318e6c4d47e0e09e4a6615d90409efe87741b559209a6c88396b3b83ac355fcaa@127.0.0.1:34487 disconnected from us due to WireProtocolErr
            	Test:       	TestInstability/maker_crashed_after_send_payment
FAIL
```

**Comment by LePremierHomme** [comment]
You should run `npm run test:sim:build:xud` in addition to `npm run test:sim:build:test`, after cleaning the volumes.

**Comment by LePremierHomme** [comment]
We can also spare your local check - once all my current PRs will be merged, the Security/Instability tests will be added to travis.

**Comment by LePremierHomme** [comment]
You can also spare your local check - once all my current PRs will be merged, the Security/Instability tests will be added to travis.

**Comment by sangaman** [comment]
> You should run `npm run test:sim:build:xud` in addition to `npm run test:sim:build:test`, after cleaning the volumes.

This is still failing with:

```
--- FAIL: TestInstability (121.08s)
    --- PASS: TestInstability/network_initialization (0.36s)
    --- FAIL: TestInstability/maker_crashed_after_send_payment (84.37s)
        actions.go:98: 
            	Error Trace:	actions.go:98
            	            				tests-instability.go:43
            	            				harnessTest.go:95
            	            				xud_test.go:160
            	Error:      	Received unexpected error:
            	            	rpc error: code = Unknown desc = Peer 021512ed8bc717c868eb1f14e3fa17fed354f804caaccfed580f41355833be83a5@127.0.0.1:37599 disconnected from us due to WireProtocolErr
            	Test:       	TestInstability/maker_crashed_after_send_payment
FAIL
```

But since this test case was already failing, and since the code looks good, if it would make things easier for you we can merge this and deal with this going forward. It'll be much easier when it's tested in Travis, thanks for that.

**Comment by LePremierHomme** [comment]
Due to the error msg I suspected you're having a stale xud version running.
But yes, let's just continue for travis integration, so we'll know better.

**Pull request merged**
