### PR TITLE
chore: generate sample config on new version

### LINKED ISSUE #498: 'sample-xud.conf' v2
- auto-update `sample-xud.conf` in github repo on version bump, in root folder
- auto-update `sample-xud.conf` in npm repo

### PR DESCRIPTION
**Pull request by sangaman**
This commit updates the publish configuration to generate a sample config file before publishing and to include it among the published files.

Edit: The new approach generates the sample config file on the `npm version` script and checks it in via git. Closes #498.

### CODE REVIEW

**Comment by kilrau** [comment]
Agree with @michael1011 , either on publishing or better even travis build (if that's possible since it'd need write permissions)

**Comment by sangaman** [comment]
I'm still leaning against committing it to source, so that we don't have to maintain it by updating it each time the default config changes, nor risk forgetting to update it and having it be out of sync.

Another option is to run `npm run config` after *install* - so that every time you install `xud` whether it be from npm or from github clone or docker, this file will be generated for you and it's guaranteed to be up to date. That seems just as good as having it in source, right? @michael1011

**Comment by sangaman** [comment]
@michael1011 See the new approach per our discussion on the weekly call. I've tested this and it works like a charm, committing any changes to the sample config file along with the version change to package.json and package-lock.json when runing `npm version`.

**Comment by sangaman** [comment]
Ahhhh it did not even occur to me that the default values differ between windows and linux. We can have 3 separate files or maybe figure out a way to get values for all 3 in the same file - it will definitely take some tweaking of the config script itself tho. Right now it will generate it for whatever OS you're running when you generate the file, which is definitely not ideal.

**Comment by sangaman** [comment]
@michael1011 I'm thinking of tweaking the config job a bit to make 3 separate files. `sample-linux-xud.conf`, `sample-win-xud.conf`, and `sample-mac-xud.conf`. Let me know if that sounds good to you.

**Comment by michael1011** [comment]
@sangaman  what do you think of putting the default values in comments above the actual value:
```
# Directory for all data stored by LightningTip (config and log file)
# Gets overwritten by individual settings and flags like: "logfile" and "config"
#
# Default values:
# Darwin (macOS): /Users/<user>/Library/Application Support/LightningTip
# Linux: /home/<user>/.lightningtip
# Windows: C:\Users\<user>\AppData\Local\LightningTip
#
# datadir =
```

Having three separate config files seems a bit messy and overkill to me since only a few values are affected by the OS.

**Comment by sangaman** [comment]
I thought about that but still have some concerns. There are quite a few actually when you count the multiple lnd `macaroonpath`/`tlscertpath` which are not derived from `xudir`. Plus it might be harder to maintain if we add more path-based config variables, my approach would be to look for "path" in the config property name but that wouldn't be 100% reliable.

Maybe I could generate only a linux file - since I figure that will be the most commonly used platform - and then put a preamble in the header similar to the one you've posted and list the various `xudir` values as well as the default directory for `lnd`. What do you think of that?

**Comment by kilrau** [comment]
I think having 3 separate samples are the best option since this doesn't require the user to think much. Don't see where it's messy. I'm ok with it. @sangaman @michael1011

**Comment by michael1011** [comment]
Yeah if you don't think it is worth the effort to put everything into one config I am also fine with one for every OS (but don't forget to run the sample config script on a Linux and Mac VM before you publish the NPM package). 

One thing that came just to my mind: the sample config would contain the user name of the one publishing the NPM package. Is that intended by you @sangaman?

**Comment by sangaman** [comment]
> One  thing that came just to my mind: the sample config would contain the user name of the one publishing the NPM package. Is that intended by you @sangaman?

Nope it's not - that's another thing I overlooked. Will definitely have to make all user-related info generic.

**Comment by sangaman** [comment]
Take a look at this again when you can, it has a single config file without any of the default paths, but with comments explaining the key path options and their defaults based on the platform.

**Comment by kilrau** [comment]
since you use `<user>` for Linux and MacOS, also do this for Win and not `Daniel` in the description:

`# macaroonpath = "C:\Users\Daniel\AppData\Local\Lnd\data\chain\<currency`

After this fine for me.

**Comment by sangaman** [comment]
Hah thanks for catching that @kilrau, thought I'd replaced it everywhere. Will fix and merge, thanks!

**Pull request merged**
