### PR TITLE
feat: ignore unavailable swap clients on create (#1815)

### LINKED ISSUE #1815: xucli doesn't work if L2 is not set up properly
### Background

I want to test xud only and don't need to use Lightning/Connext. Xucli cannot be used without the L2 systems fully functioning.

### Steps to reproduce

Clean native install of xud. Compile and run xud without first setting up L2 systems. Attempt to run xucli.

### Expected behaviour

Xud should start and connect to the xud network without requiring L2 systems.

### Actual behaviour

Xucli throws error about LTC/LND/BTC networks not being connected

Screenshot 2020-08-16 at 14 22 07

### Logs (/bin/xud)

(node:14514) ExperimentalWarning: The fs.promises API is experimental
16/08/2020 12:31:08.894 [RPC] info: gRPC server listening on localhost:28886
16/08/2020 12:31:09.107 [DB] info: connected to database /home/hatmer/.xud/xud-simnet.db
16/08/2020 12:31:09.133 [LND-BTC] debug: loaded tls cert from /home/hatmer/.lnd/tls.cert
16/08/2020 12:31:09.134 [LND-LTC] debug: loaded tls cert from /home/hatmer/.lnd/tls.cert
16/08/2020 12:31:09.135 [LND-LTC] info: could not load macaroon at /home/hatmer/.lnd/data/chain/litecoin/simnet/admin.macaroon, this is normal before creating a new wallet
16/08/2020 12:31:09.135 [LND-LTC] info: new status: Initialized
16/08/2020 12:31:09.137 [LND-LTC] info: waiting for wallet to be initialized...
16/08/2020 12:31:09.146 [RAIDEN] info: new status: Initialized
16/08/2020 12:31:09.147 [RAIDEN] info: trying to verify connection to raiden with uri: localhost:5001
16/08/2020 12:31:09.159 [RAIDEN] info: new status: Disconnected
16/08/2020 12:31:09.159 [RAIDEN] error: Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
16/08/2020 12:31:09.160 [RAIDEN] error: could not verify connection to raiden at localhost:5001, retrying in 5000 ms: Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
16/08/2020 12:31:09.161 [LND-BTC] debug: loaded macaroon from /home/hatmer/.lnd/data/chain/bitcoin/simnet/admin.macaroon
16/08/2020 12:31:09.162 [LND-BTC] info: new status: Initialized
16/08/2020 12:31:09.162 [LND-BTC] info: trying to verify connection to lnd at localhost:10009
16/08/2020 12:31:09.179 [LND-BTC] info: new status: WaitingUnlock
16/08/2020 12:31:09.180 [LND-BTC] error: could not verify connection at localhost:10009, error: {"code":12,"metadata":{"_internal_repr":{},"flags":0},"details":"unknown service lnrpc.Lightning"}, retrying in 5000 ms
16/08/2020 12:31:09.181 [GLOBAL] info: Node key is encrypted, unlock with 'xucli unlock', 'xucli create', or 'xucli restore'
16/08/2020 12:31:14.147 [RAIDEN] info: trying to verify connection to raiden with uri: localhost:5001
16/08/2020 12:31:14.149 [RAIDEN] error: Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
16/08/2020 12:31:14.150 [RAIDEN] error: could not verify connection to raiden at localhost:5001, retrying in 5000 ms: Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
16/08/2020 12:31:15.139 [LND-LTC] info: new status: WaitingUnlock
16/08/2020 12:31:19.151 [RAIDEN] info: trying to verify connection to raiden with uri: localhost:5001
16/08/2020 12:31:19.153 [RAIDEN] error: Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
16/08/2020 12:31:19.153 [RAIDEN] error: could not verify connection to raiden at localhost:5001, retrying in 5000 ms: Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
16/08/2020 12:31:23.877 [RPC] debug: received call /xudrpc.XudInit/CreateNode
16/08/2020 12:31:24.155 [RAIDEN] info: trying to verify connection to raiden with uri: localhost:5001
16/08/2020 12:31:24.157 [RAIDEN] error: Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
16/08/2020 12:31:24.163 [RAIDEN] error: could not verify connection to raiden at localhost:5001, retrying in 5000 ms: Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
16/08/2020 12:31:24.217 [LND-LTC] info: new status: Disconnected
16/08/2020 12:31:24.218 [LND-LTC] debug: error on initWallet: 14 UNAVAILABLE: failed to connect to all addresses
16/08/2020 12:31:24.218 [LND-LTC] error: could not initialize wallet: 14 UNAVAILABLE: failed to connect to all addresses
{ code: 13,
  message:
   'could not initialize lnd-LTC: 14 UNAVAILABLE: failed to connect to all addresses',
  name: 'UnknownError' }
16/08/2020 12:31:24.230 [RPC] error: call /xudrpc.XudInit/CreateNode errored with code 13: could not initialize lnd-LTC: 14 UNAVAILABLE: failed to connect to all addresses
16/08/2020 12:31:24.243 [LND-BTC] debug: error on initWallet: 2 UNKNOWN: wallet already exists
16/08/2020 12:31:24.245 [LND-BTC] error: could not initialize wallet: 2 UNKNOWN: wallet already exists
16/08/2020 12:31:29.205 [LND-LTC] error: AssertionError [ERR_ASSERTION]: awaitWalletInit should not be called from a status besides Initialized or Unlocked
    at LndClient.<anonymous> (/home/hatmer/xud/dist/lndclient/LndClient.js:358:38)
    at Generator.next (<anonymous>)
    at /home/hatmer/xud/dist/lndclient/LndClient.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/home/hatmer/xud/dist/lndclient/LndClient.js:23:12)
    at LndClient.awaitWalletInit (/home/hatmer/xud/dist/lndclient/LndClient.js:337:42)
    at LndClient.<anonymous> (/home/hatmer/xud/dist/lndclient/LndClient.js:402:30)
    at Generator.next (<anonymous>)
    at /home/hatmer/xud/dist/lndclient/LndClient.js:27:71
    at new Promise (<anonymous>)
16/08/2020 12:31:29.253 [RAIDEN] info: trying to verify connection to raiden with uri: localhost:5001
16/08/2020 12:31:29.274 [RAIDEN] error: Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
16/08/2020 12:31:29.276 [RAIDEN] error: could not verify connection to raiden at localhost:5001, retrying in 5000 ms: Error: connect ECONNREFUSED 127.0.0.1:5001
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
16/08/2020 12:31:31.735 [RAIDEN] info: created raiden keystore with master seed and empty password in /home/hatmer/.ethereum
^C16/08/2020 12:31:32.811 [GLOBAL] info: XUD is shutting down
16/08/2020 12:31:32.814 [LND-BTC] info: new status: Disconnected
16/08/2020 12:31:32.824 [CONNEXT] error: cannot set status to Disconnected from NotInitialized
16/08/2020 12:31:32.825 [CONNEXT] error: cannot set status to Disconnected from NotInitialized
16/08/2020 12:31:32.840 [RPC] info: gRPC server completed shutdown
16/08/2020 12:31:32.858 [GLOBAL] info: XUD shutdown gracefully

### PR DESCRIPTION
**Pull request by rsercano**
attempts to fix #1815 

But as a followup I don't know if this affects next startups when L2 is setup properly @sangaman

### CODE REVIEW

**Comment by erkarl** [comment]
Can we initialize all swap clients after the initial create now?

**Comment by sangaman** [comment]
> Can we initialize all swap clients after the initial create now?

Yes, thanks to #1973 we should automatically initialize wallets on future xud unlocks, so requiring all wallets/swap clients to be online upon initial create isn't that big a deal any more. So this change would make sense to me now.

**Review by sangaman — DISMISSED** [review]
The change is very straightforward to do and I think the use case makes at least some sense since wallets/swap clients that aren't initialized up front will be initialized on future unlock calls. It does mean, however, that a user could create an xud node and not have all swap clients initialized upon first run, if they want them to be initialized properly later they'll need to restart xud. But maybe that's a desirable tradeoff. The thinking originally of having this requirement was to prevent users from initializing xud without initializing all the swap clients it is using (if a swap client is enabled and configured, presumably we expect the user to want it to be initialized), the related issue changes that behavior.

Note that we still require swap clients to be online for restore calls, which makes sense to keep that restriction to help ensure we restore everything properly.

It'd be good to get a concept ACK from @kilrau about the above, but the code change here is fine.

**Comment by kilrau** [comment]
Concept ACK

**Review by kilrau — APPROVED** [review]

**Review by raladev — CHANGES_REQUESTED** [review]
Steps:
1. wait for neutrino sync
2. stop container with lndbtc
3. try to create xud wallet

- [x] I am still getting unavaliable err
```
native@ubuntu:~/xud$ ./bin/xucli create
You are creating an xud node key and underlying wallets. All will be secured by a single password provided below.

Enter a password: 
Re-enter password: 

Error: 13 INTERNAL: could not initialize lnd-BTC: 14 UNAVAILABLE: failed to connect to all addresses
native@ubuntu:~/xud$ ./bin/xucli getbalance
xud is locked, run 'xucli unlock', 'xucli create', or 'xucli restore' then try again

native@ubuntu:~/xud$ ./bin/xucli unlock
Enter master xud password: 
no xud node exists to unlock, try creating one with 'xucli create' or 'xucli restore'
native@ubuntu:~/xud$ 
```

- [ ] also it would be good if u fix assertion for auto-post-create flow
```
24/11/2020 09:32:03.099 [LND-BTC] error: AssertionError [ERR_ASSERTION]: awaitWalletInit should not be called from a status besides Initialized or Unlocked
    at LndClient.<anonymous> (/home/native/xud/dist/lndclient/LndClient.js:369:38)
    at Generator.next (<anonymous>)
    at /home/native/xud/dist/lndclient/LndClient.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/home/native/xud/dist/lndclient/LndClient.js:23:12)
    at LndClient.awaitWalletInit (/home/native/xud/dist/lndclient/LndClient.js:348:42)
    at LndClient.<anonymous> (/home/native/xud/dist/lndclient/LndClient.js:413:30)
    at Generator.next (<anonymous>)
    at /home/native/xud/dist/lndclient/LndClient.js:27:71
    at new Promise (<anonymous>)
```

**Comment by rsercano** [comment]
@raladev are you sure you have the correct changeset? I have the exact same condition and don't get an error:

image
image

**Comment by raladev** [comment]
checked once more, same result.
[Screenshot from 2020-11-25 21-55-33](https://user-images.githubusercontent.com/29906866/100270494-33ad5080-2f69-11eb-9ad9-9515ab0090c4.png)
[Screenshot from 2020-11-25 21-55-21](https://user-images.githubusercontent.com/29906866/100270499-35771400-2f69-11eb-92b9-008142564341.png)

Yeap, im sure that am in same changeset.
```
native@ubuntu:~/xud$ git log -1
commit f7b955b89236861c33226e14bc105ae77c372f24 (HEAD -> fix/create-node-ignore-unavailable-clients, origin/fix/create-node-ignore-unavailable-clients)
Author: rsercano <ozdemirsercan27@gmail.com>
Date:   Tue Nov 24 12:51:05 2020 +0300

    fix: ignores unavailable swap clients during create node (#1815)

```
U have a little bit differrent condition, in your case both lnd are not avaliable, in my case only lndbtc is not avaliable.

My steps:
0. share lnd port through simnet.conf - https://docs.exchangeunion.com/development/developer-guide
1. bash xud.sh 
2. wait for neutrino sync
3. close utils
4. docker rm -f simnet_xud_1
5. docker stop simnet_lndbtc_1
6. git clone https://github.com/ExchangeUnion/xud.git
7. mkdir .xud & cd ./xud
8. nano xud.conf - set pathes to lndbtc and lndltc certs
```
loglevel = "trace"
noencrypt = false

[http]
host = "localhost"
port = 8887

[lnd.BTC]
cltvdelta = 40
disable = false
host = "localhost"
nomacaroons = false
port = 30009
certpath = "/home/native/.xud-docker/simnet/data/lndbtc/tls.cert"
macaroonpath = "/home/native/.xud-docker/simnet/data/lndbtc/data/chain/bitcoin/simnet/admin.macaroon"

[lnd.LTC]
cltvdelta = 576
disable = false
host = "localhost"
nomacaroons = false
port = 31009
certpath = "/home/native/.xud-docker/simnet/data/lndltc/tls.cert"
macaroonpath = "/home/native/.xud-docker/simnet/data/lndltc/data/chain/litecoin/simnet/admin.macaroon"

[raiden]
disable = true

[connext]
disable = false
host = "localhost"
port = 25040

[debug]
testing = false
```
9. cd ~/xud
10. git checkout fix/create-node-ignore-unavailable-clients
11. npm install & npm run compile & npm run compile:seedutil  https://docs.exchangeunion.com/development/native-installation
12. sudo ./bin/xud
13. sudo ./bin/xucli create

**Comment by rsercano** [comment]
Thanks for sharing all steps briefly Roman I will check it.

25 Kas 2020 Çar 22:06 tarihinde raladev <notifications@github.com> şunu
yazdı:

**Comment by rsercano** [comment]
I changed how `initWallets` in `SwapClientManager` behave while initializing by removing `throw error` phrase, therefore it won't throw while initializing a wallet per swap client and create/restore commands should continue as is, if one of the clients is not available for initializing. 

@raladev @sangaman

**Review by raladev — APPROVED** [review]

**Comment by kilrau** [comment]
Could you please give this another look? @sangaman

**Comment by sangaman** [comment]
This error `24/11/2020 09:32:03.099 [LND-BTC] error: AssertionError [ERR_ASSERTION]: awaitWalletInit should not be called from a status besides Initialized or Unlocked` is unrelated to this PR - I'll look into it separately. It's a bit of an edge case but I can reproduce it by setting up a new node with an enabled lnd in the config that is unreachable. It's setting the state of that lnd to `WaitingUnlock` when it should really be disconnected, so it tries to unlock it anyway and hits that exception.

Sercan's workaround to remove the `throw` line is fine for now, but I think it would make sense to reenable it once the above is addressed.

**Review by sangaman — APPROVED** [review]

**Pull request merged**
