### PR TITLE
Refactor enums to use typescript

### PR DESCRIPTION
**Pull request by sangaman**
Just some typescript housecleaning. I think this is one of the last remaining parts of the code that hadn't been migrated over to using typescript conventions.

### CODE REVIEW

**Comment by moshababo** [comment]
I think it should be moved to `types` folder, no?

**Comment by sangaman** [comment]
Yes that makes sense actually. What do you think about making `errorCodesPrefix` an enum as well and scrapping the `constants` folder for now? @moshababo

**Comment by moshababo** [comment]
I'm not sure it should be made a enum. But we should change the way it's currently being used by the errors files (more OOP, now with TS).

**Comment by sangaman** [comment]
OK, yeah I suppose an enum wouldn't be appropriate for how we're using `errorCodesPrefix`, so I'll just leave that out of this PR and we can take care of that separately. I moved `enums` to the `types` folder.

**Pull request merged**
