### PR TITLE
Lnd wallet api wrapper 

### LINKED ISSUE #912: `xud` master password
Needs some research if this could work like this @sangaman :

* let's btclnd create memonic, use it for xud and inject it in all other non-preexisting nodes
* encrypts xud's private key and all other nodes non-preexisting nodes private key with `xud` master password
* lnd macaroons, full-node rpc passwords
* pre-existing LND/raiden/fullnode's: user has to enter passwords and xud stores and encrypts these pws with master password. Needs great explainer on what is happening here and why this is secure.
* as just discussed, this should be a xud core function exposed as gRPC and CLI call

### PR DESCRIPTION
**Pull request by ImmanuelSegol**
EDIT (by @kilrau ): closes #912

### CODE REVIEW

**Comment by sangaman** [comment]
I'm a bit unclear as to the scope of this PR, could you elaborate a bit before I review? Also the tests are currently failing due to compilation errors, could you clear those up?

**Comment by ImmanuelSegol** [comment]
> I'm a bit unclear as to the scope of this PR, could you elaborate a bit before I review? Also, the tests are currently failing due to compilation errors, could you clear those up?

It's not ready for review yet, @kilrau stated in issue #40 that we should create wrapper commands for specific LND commands.

**Comment by sangaman** [comment]
Ah OK I missed the WIP in the PR title. When you get a chance it'd still be good to get an overview of what's being changed and added to have context

**Comment by kilrau** [comment]
Any updates here? We would need these calls for the docker setup soonish @ImmanuelSegol

**Comment by ImmanuelSegol** [comment]
> Any updates here? We would need these calls for the docker setup soonish @ImmanuelSegol

Will complete this today as well.

> Any updates here? We would need these calls for the docker setup soonish @ImmanuelSegol
@kilrau Yeah test it to make sure everything works well.

**Comment by kilrau** [comment]
I think it should be clear from [the original issue](https://github.com/ExchangeUnion/xud/issues/40) that we decided to NOT integrate all `lnd` client calls, but only the ones that matter.

What might have not been clear: integrating a call shouldn't be 1-1, because that would indeed require the user to learn `lncli`, which doesn't make wrapping very meaningful in the first place. What makes it meaningful: we can simplify lnd client calls a lot and consequently use `xucli` syntax.

I suggest as a next step for you to go over the [relevant calls I listed](https://github.com/ExchangeUnion/xud/issues/40#issuecomment-482053134) and propose a syntax and info the call should have with an example each. @reliveyy @sangaman and I will then go and check to make sure this meets the use case, because @sangaman was perfectly right - they are very use case specific; mainly #912. Let me give you an example what I mean by 'simplify': the user should never have to provide a peer's LND URI, all should be automatically mapped internally by providing `xud` `NodePubKey` only.

So please go ahead and list the calls with samples here and we'll help you to finalize these. Not all calls [I listed](https://github.com/ExchangeUnion/xud/issues/40#issuecomment-482053134) are needed immediately, so we can leave them out for now. To make it simple, I closed #40 because it was too generic and we make this issue about wrapping calls for the #912 use case. All other calls we'll need after, we play it by ear - as soon as we have a use case, we'll add it.

**Comment by kilrau** [comment]
Also since it's targeting #912 now, this PR should include wrappers for `geth` with the same functionality. Maybe change the title to something more generic like "Layer1/2 client api wrapper"

**Comment by kilrau** [comment]
Here an update list of lnd calls that should be exposed in a simplified manner via xud's grpc:

https://api.lightning.community/#genseed
https://api.lightning.community/#initwallet
https://api.lightning.community/#unlockwallet
https://api.lightning.community/#walletbalance
https://api.lightning.community/#gettransactions
https://api.lightning.community/#estimatefee
https://api.lightning.community/#sendcoins
https://api.lightning.community/#newaddress
https://api.lightning.community/#subscribechannelbackups (for #246 )

Anything missing for #912 @sangaman @erkarl ?

**Comment by kilrau** [comment]
aight, so close this PR and include in new and existing issues? @erkarl @ImmanuelSegol

**Pull request closed without merging**
