### PR TITLE
Added Auto-Restart section to Readme #46

### LINKED ISSUE #46: Auto-restart support
When running multiple `xud` instances on one machine, it's necessary to do so with  `~/xud/bin $ ./xud` symlink, so that the distinguishing args can be used (rpc.port, p2p.port) for the different instances. When trying to run `nodemon` on it, it does not detect file changes.

### PR DESCRIPTION
**Pull request by rsercano**
fixes #46 

- Added to the readme,

@kilrau But couldn't add for typedoc, since typedoc is an auto generated documentation from codes, where should I add this information in the code since we didn't do any change on code ?

### CODE REVIEW

**Comment by rsercano** [comment]
then it's mergable, what do you think @kilrau ?

**Comment by kilrau** [comment]
Looks good!

**Comment by rsercano** [comment]
Thx @kilrau, just requested the claim from fundrequest, thx for merging :)

**Comment by kilrau** [comment]
np, keep up the good work - feel free to help us testing - we plan to have a first release soon 🥇

**Comment by rsercano** [comment]
Will do for sure @kilrau ! :)

**Pull request merged**
