### PR TITLE
fix(orderbook): show aggregated quantity

### PR DESCRIPTION
**Pull request by ghost**
As discussed with @kilrau in this PR we remove the `depth` column from the orderbook and replace it with `volume` instead.

Previously we displayed `price * quantity` per price point, but what we actually want is all available quantity at one price point aggregated.

### CODE REVIEW

**Review by kilrau — CHANGES_REQUESTED** [review]
Tested, works as it should! Minor nit: let's swap the price and volume column for 'Buy', that puts the prices next to each other like on other orderbooks and one can see easier.

```
Trading pair: LTC/BTC
┌───────────────────────────────────────┬───────────────────────────────────────┐
│ Buy                                   │ Sell                                  │
├───────────────────┬───────────────────┼───────────────────┬───────────────────┤
│   Volume            │ Price           │ Price             │ Volume            │
├───────────────────┼───────────────────┼───────────────────┼───────────────────┤
│  2           │ 0.0078                 │ 0.00785           │ 1                 │
├───────────────────┼───────────────────┼───────────────────┼───────────────────┤
│ 3.5           │ 0.0077               │ 0.0079            │ 2                 │
```

**Comment by kilrau** [comment]
Reference orderbook: https://www.kraken.com/prices

**Review by sangaman — COMMENTED** [review]
"Volume" in a trading context sounds to me like the amount that has been traded, not the amount that's available to trade. I know that's the term Kraken is using, but that still seems like non-standard usage of the word (reference: https://www.investopedia.com/terms/v/volume.asp).

Coinbase uses "Market Size" for this term and bitfinex uses "Amount" for this purpose. I'd be fine with either of those, or maybe just "Quantity". So I'd prefer to use one of those terms and just use the new way of calculating it (without multiplying by price).

I also agree with Kilian's suggestion to have the two price columns adjacent to each other.

**Comment by kilrau** [comment]
> I'd be fine with either of those, or maybe just "Quantity".

Agree, let's stick with "Quantity" then, because that's what we use in `listorders` already.

Also, I don't think our `xucli help` description of `listorders` and `orderbook` is distinctive/descriptive enough. I'd go for sth along the lines
`xucli listorders [pair_id] [include_own_orders] [limit]    list orders from the order book` (no change)
`xucli orderbook [pair_id] [precision]    display the order book, with orders aggregated per price point`

Summary of quick fixes:
- [ ] Volume -> Quantity
- [ ] Switch `Price` and `Quantity` column for `Buy`
- [ ] `xucli help` `orderbook` command description

**Comment by erkarl** [comment]
Rebased and updated.

**Review by kilrau — APPROVED** [review]
LGTM!

**Review by moshababo — APPROVED** [review]

**Review by sangaman — APPROVED** [review]
Thanks!

**Pull request merged**
