### PR TITLE
Fixed travis build

### PR DESCRIPTION
**Pull request by michael1011**
This PR will Travis make install `rsync` before compiling the Docker image and cause the build to succeed.

### CODE REVIEW

**Comment by sangaman** [comment]
Thanks, I was wondering if this was a temporary issue with travis as the grpc2 branch was building fine even after I added the `rsync`command, but this is probably good to have to be sure.

**Comment by michael1011** [comment]
The build still fails for some reason. What about using `cp` instead of `rsync` on Linux and Mac?

**Comment by sangaman** [comment]
Hmm I'll look into it later, it looks like it might an issue with the docker build actually. I'm not sure if it's possible to do that same command with `cp`, in other words copying over the directory structure and only files matching the `.js` extension, but I'll look into that too.

**Comment by michael1011** [comment]
I should have installed `rsync` in the Docker container and not on the Travis VM :man_facepalming: 

Adding `RUN apt update && apt install -y rsync` to the Dockerfile solves this issue

**Comment by sangaman** [comment]
Good call, want to just open a separate PR reverting the line from this one and adding the one above to the dockerfile? Your PR's travis builds should happen now.

**Pull request merged**
