### PR TITLE
Generate Swagger

### LINKED ISSUE #133: Swagger API Docs for Web API Proxy
The idea is to generate `Swagger REST API` documentation for web API proxy from the `proto` file.
This would involve.

- Generation of swagger json file from `protoc` via [protoc-gen-swagger](https://github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger)
       Example: `protoc DEFINITION.proto --swagger_out=logtostderr=true:.`
- Attach Swagger Docs Middleware to `webproxy / express` for serving the documentation.

### PR DESCRIPTION
**Pull request by sangaman**
Closes #133. This PR updates some comments and adds a script to generate a swagger definition from our proto file.

### CODE REVIEW

**Comment by moshababo** [comment]
Can we serve the swagger file on the express server?

**Comment by sangaman** [comment]
Yeah, thoughts on using this package: https://www.npmjs.com/package/swagger-ui-express?

**Comment by moshababo** [comment]
Didn't use it myself but looks fine.

**Comment by itsbalamurali** [comment]
@sangaman  looks good overall but I think it would be complete if you include the `swagger-ui-express` to serve the generated swagger file. which would complete issue #133

**Comment by sangaman** [comment]
Added `swagger-ui-express` and tested that the file gets served at the `/api-docs` endpoint.

**Pull request merged**
