### PR TITLE
Adds aliases to list orders

### LINKED ISSUE #643: Listorders CLI output - peerpubkey
After #600, our `getorders` CLI output looks like this:

image

I'm thinking it would be nice to show which peer the owner belongs to. We could probably repurpose the `Own Order` column for this. Maybe change the label to something like "Owner" or "Peer" and print the node's peer pub key for peer orders, and "Own" or "Local" for own orders. It may even be worth taking it a step further and printing the peer's alias if one exists - however we don't have that data currently available from the `getorders` rpc call. If we think it's worth it, we could make cli command also call `listpeers` to get all the aliases and then map them to the pubkeys.

Thoughts @erkarl @kilrau @offerm?

### PR DESCRIPTION
**Pull request by rsercano**
resolves #643 

This's blocked by #486

### CODE REVIEW

**Comment by sangaman** [comment]
If we go with putting aliases in the `listorders` output, I think it would be better to keep the current rpc calls as is and instead have the cli make separate calls to get node info for the pubkeys it gets back from the `ListOrders` call.

**Comment by rsercano** [comment]
I think this should be fully clarified @sangaman

**Comment by kilrau** [comment]
In general I would not want to have the CLI calls differ much from the underlying gRPC calls but in the case of `alias`, I agree since it's purely for the user.

So yes, whenever we want to show an alias to the user, we can use other rpc calls to get it.

**Comment by kilrau** [comment]
How it is:
```
Trading pair: ETH/BTC
┌────────────────────────────────────────────────────┬────────────────────────────────────────────────────┐
│ Buy                                                │ Sell                                               │
├───────────────────┬───────────────────┬────────────┼───────────────────┬───────────────────┬────────────┤
│ Quantity          │ Price             │ Own Order  │ Quantity          │ Price             │ Own Order  │
├───────────────────┼───────────────────┼────────────┼───────────────────┼───────────────────┼────────────┤
│ 0.001             │ 2                 │            │ 0.001             │ 2                 │            │
├───────────────────┼───────────────────┼────────────┼───────────────────┼───────────────────┼────────────┤
│                   │                   │            │ 0.001             │ 2                 │            │
└───────────────────┴───────────────────┴────────────┴───────────────────┴───────────────────┴────────────┘
```

How we want it:
```
Trading pair: ETH/BTC
┌────────────────────────────────────────────────────┬────────────────────────────────────────────────────┐
│ Buy                                                │ Sell                                               │
├───────────────────┬───────────────────┬────────────┼───────────────────┬───────────────────┬────────────┤
│ Quantity          │ Price             │ Own Order  │ Quantity          │ Price             │ Own Order  │
├───────────────────┼───────────────────┼────────────┼───────────────────┼───────────────────┼────────────┤
│ 0.001             │ 2                 │            │ 0.001             │ 2                 │            │
├───────────────────┼───────────────────┼────────────┼───────────────────┼───────────────────┼────────────┤
│                   │                   │            │ 0.001             │ 2                 │            │
└───────────────────┴───────────────────┴────────────┴───────────────────┴───────────────────┴────────────┘
```

**Comment by sangaman** [comment]
Closing this PR since it's incomplete and somewhat dated, I'll open another one to resolve the same issue.

**Pull request closed without merging**
