### PR TITLE
feat(backup): write xud db every 3 minutes max

### LINKED ISSUE #1368: Throttle xud-backup update interval
Currently `xud-backup` updates immediately when changes to the file are detected. This could be problematic for larger database files (100mb+).

### PR DESCRIPTION
**Pull request by sangaman**
This changes the behavior of the xud backup from backing up the xud db every time it changes (which is very often) to every 3 minutes, provided that it has changed in the preceding 3 minutes. Note that this approach still needs refinement to prevent corrupted backups as described in issue #1652.

Closes #1368.

### CODE REVIEW

**Comment by kilrau** [comment]
You can run this with `bash xud.sh -b backup/xud-db-timer` once https://travis-ci.org/github/ExchangeUnion/xud-docker/builds/697757895 passed.

**Comment by kilrau** [comment]
Tested this today on the same setup from yesterday:
- maker on fast-disk machine
- taker on a slow disk machine

Swaps are still comparably slow but much faster compared to yesterday (about 10s total time to complete). Nowhere near the 30s timeout.

**Comment by kilrau** [comment]
Backup tests need to be adjusted:
```
  ● Backup › should write XUD database backups on new event

    Failed: undefined

      149 |   });

      150 | 

    > 151 |   test('should write XUD database backups on new event', async () => {

          |   ^

      152 |     fs.writeFileSync(

      153 |       xudDatabasePath,

      154 |       backups.xud.event,

      at Env.it (../../node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:89:24)

      at Suite.<anonymous> (Backup.spec.ts:151:3)

      at Object.<anonymous> (Backup.spec.ts:60:1)
```

And can you comment out that raiden db test for now?
```
FAIL  test/jest/Backup.spec.ts (6.527 s)

  ● Backup › should write Raiden backups on startup

    ENOENT: no such file or directory, open 'backup-test/raiden'

      109 |   test('should write Raiden backups on startup', () => {

      110 |     expect(

    > 111 |       fs.readFileSync(

          |          ^

      112 |         path.join(backupdir, 'raiden'),

      113 |         'utf8',

      114 |       ),

      at Object.<anonymous> (Backup.spec.ts:111:10)

  ● Backup › should write Raiden backups on new event

    Failed: undefined

      116 |   });

      117 | 

    > 118 |   test('should write Raiden backups on new event', async () => {

          |   ^

      119 |     fs.writeFileSync(

      120 |       raidenDatabasePath,

      121 |       backups.raiden.event,

      at Env.it (../../node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:89:24)

      at Suite.<anonymous> (Backup.spec.ts:118:3)

      at Object.<anonymous> (Backup.spec.ts:60:1)

  ● Backup › should write XUD database backups on new event

    Failed: undefined

      149 |   });

      150 | 

    > 151 |   test('should write XUD database backups on new event', async () => {

          |   ^

      152 |     fs.writeFileSync(

      153 |       xudDatabasePath,

      154 |       backups.xud.event,

      at Env.it (../../node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:89:24)

      at Suite.<anonymous> (Backup.spec.ts:151:3)

      at Object.<anonymous> (Backup.spec.ts:60:1)
```

**Comment by michael1011** [comment]
> Backup tests need to be adjusted:
These tests should be either removed completely or need to be rewritten since the functionality of the backup daemon changed.

**Comment by sangaman** [comment]
I updated the tests to conform to the new backup approach.

**Comment by kilrau** [comment]
https://github.com/ExchangeUnion/xud/pull/1655#pullrequestreview-430129981 still needs to be addressed though. Can do some more testing today if required.

**Comment by sangaman** [comment]
@kilrau In my tests I confirmed this is only updating the backup at most every 3 minutes, can you please double check on your end if you're still seeing that behavior? And confirm xud is on commit `cfdf8b6c6bb9ed1a2c7f7b1a512504a387b5074b`.

**Pull request merged**
