### PR TITLE
prealpha.1 -> prealpha.2

### PR DESCRIPTION
**Pull request by kilrau**
As discussed with @sangaman we'll stick with the version of the last release on current master. Please check and merge this since I want to update our seed notes to advertise the correct version

### CODE REVIEW

**Comment by sangaman** [comment]
I'd prefer just publishing a prealpha.3 and updating the version then actually. There are a number of fixes plus a change in how the code is packaged.

**Comment by kilrau** [comment]
Ready to do this or still waiting for sth?

**Comment by sangaman** [comment]
Just doing a lot of other things at this moment, I can do it tonight or you can go ahead. Although maybe lets at least wait for #372 because that's a significant UX improvement.

**Comment by kilrau** [comment]
K, let's wait for @michael1011 's #372 . Let's do the npm versioning together again, want to see what I did wrong last time

**Comment by kilrau** [comment]
We'll wait for `alpha.1`

**Pull request closed without merging**
