### PR TITLE
fix: propagating currencies and pairs on database if initDB true even…

### LINKED ISSUE #1917: Propagate new seed currencies & pairs on existing db
As a follow-up of https://github.com/ExchangeUnion/xud/pull/1907 we want to apply this behaviour to `currencies` & `pairs` in `seeds` too: [add new ones, don't touch existing ones](https://github.com/ExchangeUnion/xud/issues/1645#issuecomment-694735517)

### PR DESCRIPTION
**Pull request by rsercano**
resolves #1917

### CODE REVIEW

**Review by erkarl — CHANGES_REQUESTED** [review]
1. Modify seeds file to only include currencies and pairs for BTC/LTC/ETH
2. Create fresh xud env
3. Close xud
4. Edit seeds file to include currencies and pairs for USDT
5. Start xud
6. ERROR:
```
> node dist/Xud.js

28/09/2020 09:18:28.346 [GLOBAL] info: config file loaded
28/09/2020 09:18:28.354 [RPC] info: gRPC server listening on localhost:8886
28/09/2020 09:18:28.403 [DB] info: connected to database /home/ar/.xud/xud-simnet.db
28/09/2020 09:18:28.422 [GLOBAL] error: Unexpected error during initialization, shutting down...: SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/home/ar/xud/node_modules/sequelize/lib/dialects/sqlite/query.js:409:16)
    at Query._handleQueryResponse (/home/ar/xud/node_modules/sequelize/lib/dialects/sqlite/query.js:72:18)
    at Statement.afterExecute (/home/ar/xud/node_modules/sequelize/lib/dialects/sqlite/query.js:246:27)
28/09/2020 09:18:28.423 [GLOBAL] info: XUD is shutting down
28/09/2020 09:18:28.423 [RPC] info: gRPC server completed shutdown
28/09/2020 09:18:28.425 [GLOBAL] info: XUD shutdown gracefully
```

**Comment by rsercano** [comment]
Sorry completely my bad @erkarl, fixed now

**Review by raladev — APPROVED** [review]

**Review by sangaman — APPROVED** [review]
LGTM

**Review by erkarl — APPROVED** [review]
Perfect, thanks.

**Pull request merged**
