### PR TITLE
test(sim): export lnd instances logs

### PR DESCRIPTION
**Pull request by LePremierHomme**
Export test run bitcoin/litecoin lnd instances logs under `test/simulation/temp/logs` (available for print via `npm run test:sim:logs`).

---

Part of https://github.com/ExchangeUnion/xud/issues/1356

### CODE REVIEW

**Comment by LePremierHomme** [comment]
Yes, it's the same as before - it just export everything, and it's up to you to cleanup the folder whenever you want.
I thought that printing is just for cloud debugging (travis), since it's much less comfortable than manually picking the files you want to look at (instead of seeing them all at once). 
If you think otherwise, and you want filtered printing, let me know which indexes you're interested in (node name, etc.). If not, we can leave it as is.

**Comment by sangaman** [comment]
> Yes, it's the same as before - it just export everything, and it's up to you to cleanup the folder whenever you want.
> I thought that printing is just for cloud debugging (travis), since it's much less comfortable than manually picking the files you want to look at (instead of seeing them all at once).
> If you think otherwise, and you want filtered printing, let me know which indexes you're interested in (node name, etc.). If not, we can leave it as is.

I think it's fine, I was mostly just wondering. I think the one thing that might be nice to do if not too much trouble is to only print the logs from the most recent run on this command.

**Comment by LePremierHomme** [comment]
This will require to persist somewhere the last run id.. it will require some additional code. Let me know if you want this.

**Comment by sangaman** [comment]
> This will require to persist somewhere the last run id.. it will require some additional code. Let me know if you want this.

It's OK for now, like I said not worth it if it's much work to implement.

**Pull request merged**
