### PR TITLE
fix(lnd): totalOutboundAmount

### LINKED ISSUE #1636: LND balancecheck on placeorder to not include inactive/closed channelbalance
This issue is about fixing the current lnd balancecheck on placeorder which allows me to place order with inactive/closed channels channels.

As @sangaman mentioned in https://github.com/ExchangeUnion/xud/issues/1609#issuecomment-642434598 :
This is a little more involved, we'd need to stop relying on the `ChannelBalance` lnd call since it always includes inactive channel balance. Would we want to switch to the logic for determining trading limits as the new lnd heartbeat call? It will continuously update our trading capacities/limits more precisely than `ChannelBalance` can.

Which is probably what we would need to do. Low prio, no milestone/project for now.

### PR DESCRIPTION
**Pull request by ghost**
Fixes https://github.com/ExchangeUnion/xud/issues/1636

Updating the `totalOutboundAmount` was missing from the original PR. In this context I think it makes sense to set it to `maximumOutboundAmount`. I originally thought about removing `totalOutboundAmount` field from the swap client, but connext swap client relies on it for multi currency support.

### CODE REVIEW

**Review by sangaman — DISMISSED** [review]
Thanks. I'm only wondering if it makes sense to set this to the sum of all outbound amounts, reflecting the possibility of AMP payments and/or orders that can be filled piece by piece.

**Comment by kilrau** [comment]
I think that makes sense. Sum of all outbound amounts=max sell and sum of all inbound amounts=max buy.

**Comment by erkarl** [comment]
> I think that makes sense. Sum of all outbound amounts=max sell and sum of all inbound amounts=max buy.

Oh yeah, since we have AMP now we can possibly fill those orders.

**Comment by erkarl** [comment]
> Thanks. I'm only wondering if it makes sense to set this to the sum of all outbound amounts, reflecting the possibility of AMP payments and/or orders that can be filled piece by piece.

Updated the PR accordingly.

**Review by raladev — APPROVED** [review]

**Review by sangaman — APPROVED** [review]

**Pull request merged**
