### PR TITLE
feat(rpc): subscribeSwapsAccepted

### LINKED ISSUE #1662: SubscribeSwapsAccepted
A streaming call that would notify every time a swap is accepted with some basic info like order id, pair, amount...

### PR DESCRIPTION
**Pull request by sangaman**
This introduces a new streaming call that notifies listeners when a swap is accepted. This allows market makers to anticipate when trades will be completed earlier, as there may be a delay of 15-30 seconds between when a swap is accepted and when it is completed.

Closes #1662.

I still want to do some more manual testing before this is merged but it should be ready for review. It can be tested via cli with the `streamorders` call.

### CODE REVIEW

**Comment by erkarl** [comment]
We already have an issue for the simtests port conflict: https://github.com/ExchangeUnion/xud/issues/1721

**Comment by raladev** [comment]
- [ ] no SwapDealAccepted msg in streamorders call for taker (works for maker).
[Screenshot from 2020-07-13 20-36-53](https://user-images.githubusercontent.com/29906866/87335557-2f980d80-c549-11ea-817f-a3c000f5c2da.png)

- [ ] streamorders stream crashed after some time (1 hour), but I am not sure that this problem is connected with  SwapDealAccepted msg
[Screenshot from 2020-07-13 20-28-00](https://user-images.githubusercontent.com/29906866/87335597-3f175680-c549-11ea-9103-e2b5e9c1efd9.png)

**Comment by erkarl** [comment]
> no SwapDealAccepted msg in streamorders call for taker (works for maker).

I believe we can only accept a swap as a maker. The same thing for the taker would be sending the swap request (trying to take the order).

**Comment by raladev** [comment]
> > no SwapDealAccepted msg in streamorders call for taker (works for maker).
> 
> I believe we can only accept a swap as a maker. The same thing for the taker would be sending the swap request (trying to take the order).

https://opendex.network/read/04-swap-protocol

If i understood correctly, taker should receive SwapAccepted packet and this action should be displayed in streamorders call.

Sentence form misbehaviour table:
"Taker doesn't start the swap after receiving the SwapAccepted message"

**Comment by sangaman** [comment]
Sorry that I wasn't clear, but at least the way it's designed now it only triggers the swap accepted event on the maker side upon accepting a swap request.

An event for when a swap that we requested (as taker) is accepted might be a nice feature as part of the `PlaceOrder` flow, right now we have events for when we have an order match, when a swap fails, and when a swap is rejected, but not when a swap request is accepted.

**Comment by raladev** [comment]
> Sorry that I wasn't clear, but at least the way it's designed now it only triggers the swap accepted event on the maker side upon accepting a swap request.
> 
> An event for when a swap that we requested (as taker) is accepted might be a nice feature as part of the `PlaceOrder` flow, right now we have events for when we have an order match, when a swap fails, and when a swap is rejected, but not when a swap request is accepted.

Gotcha, then all is fine and i will create separate issue for streamorders call crash.

**Pull request merged**
