### PR TITLE
fix: getinfo output for lnd channels (#1940)

### LINKED ISSUE #1940: `getinfo` - LND Channels formatted output optimization
Currently the lnd channel overview shows 3 values: `Active`, `Pending`, `Closed` no matter if any of these categories actually have channels. In the example below I just started the environment and my channels were inactive for some minutes - I couldn't see them in the formatted output.

Formatted:
```
├──────────┼───────────────────────────────────────────────────────────────────────┤
│ Channels │ Active: 0 | Pending: 0 | Closed: 2                                    │
├──────────┼───────────────────────────────────────────────────────────────────────┤
```

JSON:
```
        "channels": {
          "active": 0,
          "inactive": 1,
          "pending": 0,
          "closed": 2
        },
```

This issue is about showing `Pending`, `Inactive` & `Closed` channels if there are non-zero values for these fields in the formatted output, don't show these if the value is 0. `Active` is always shown, no matter if zero or non-zero.

### PR DESCRIPTION
**Pull request by rsercano**
resolves #1940

### CODE REVIEW

**Comment by raladev** [comment]
- [ ] add inactive to the list
Screenshot from 2020-10-22 14-09-56

**Review by raladev — CHANGES_REQUESTED** [review]
above

**Comment by rsercano** [comment]
good catch @raladev I'll fix asap, today is a bit busy for me sorry.

**Comment by rsercano** [comment]
added @raladev thank you

**Review by raladev — APPROVED** [review]

**Review by erkarl — APPROVED** [review]

**Pull request merged**
