### PR TITLE
Cli/aliases

### PR DESCRIPTION
**Pull request by hatmer**
EDIT by @kilrau : Closes https://github.com/ExchangeUnion/xud/issues/486

Implements aliases in CLI for display by listpeers, getnodeinfo. Aliases can also be used interchangeably with public key by ban, unban, openchannel, getnodeinfo, and discovernodes.

### CODE REVIEW

**Comment by hatmer** [comment]
Do we want capitalisation to matter? Currently exact capitalisation is required but perhaps it is nicer to allow any capitalisation.
Untitled

**Comment by kilrau** [comment]
Arbitrary capitalisation is much better! What is an easy way to test this?

**Comment by kilrau** [comment]
Could you give this a rebase? @hatmer and then check that the tests pass?

**Comment by kilrau** [comment]
Want to close here in favor of https://github.com/ExchangeUnion/xud/pull/1362 ? @hatmer

**Comment by hatmer** [comment]
My rebase pulled in some unexpected commits, which it turns out is is a bug/feature of git that is changed in the most recent version of git. I ended up creating a new branch and PR [here](https://github.com/ExchangeUnion/xud/pull/1362) which nearly passes all tests

**Pull request closed without merging**
