### PR TITLE
feat(lnd): SendPaymentV2

### LINKED ISSUE #1590: LND: switch to https://api.lightning.community/#sendpaymentv2
EDIT: lndbtc & lndltc are upgraded to 0.11 and from that perspective we are ready to enable MPP. Question now is if to move to the streaming call `sendpaymentv2` since MPP is currently **not** available in the sync version `sendpaymentsync`. TBD if it ever will be (see https://github.com/ExchangeUnion/xud/issues/1590#issuecomment-680199496).

### PR DESCRIPTION
**Pull request by sangaman**
This migrates the call we use to send payments with lnd from the deprecated `SendPaymentSync` to `SendPaymentV2` which allows for multi path payments, among other improvements. As part of this change, the lnd proto files have been updated to their v0.11.x versions and the version of lnd used in simulation tests has been updated to v0.11.1 as well.

Closes #1590.

I'll open a related PR to our lnd config in xud-docker to enable MPP.

Simulation tests aren't running on my machine with these changes, so I'm opening this as a draft to see if there's any difference running them on GitHub Actions. I'll mark it as ready once I get simulation tests pasing.

### CODE REVIEW

**Comment by sangaman** [comment]
Simulation tests are passing now so this is ready for review/further testing. I'm working on a simulation test case for a multi path payments but unless I get it working soon it'd make sense to leave for a future PR.

**Review by raladev — APPROVED** [review]
- old logic works fine
- we still need the solution for route finding when user has multi path

**Review by erkarl — COMMENTED** [review]
Looks good, but needs a rebase.

**Comment by sangaman** [comment]
I'll fix the conflict and merge, it'll need another quick approval afterwards.

**Comment by sangaman** [comment]
Rebased to fix the conflict. Just needs an approval then we can merge this.

**Review by erkarl — APPROVED** [review]

**Pull request merged**
