### PR TITLE
chore(connext): add integration tests for withdraw

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by sangaman — APPROVED** [review]
Looks good, I think the commit can be a `test` rather than `chore` though for the message.

**Comment by erkarl** [comment]
> Looks good, I think the commit can be a test rather than chore though for the message.

Oops, good point. Was about to change this, but this got merged.

**Comment by raladev** [comment]
> > Looks good, I think the commit can be a test rather than chore though for the message.
> 
> Oops, good point. Was about to change this, but this got merged.

I changed commit message before merging

**Comment by erkarl** [comment]
> > > Looks good, I think the commit can be a test rather than chore though for the message.
> > 
> > 
> > Oops, good point. Was about to change this, but this got merged.
> 
> I changed commit message before merging

Double oops, thanks.

**Pull request merged**
