### PR TITLE
feat(tests): upgrade connext simtests to 7.3.6

### PR DESCRIPTION
**Pull request by ghost**
Test locally:
```
npm run test:sim:clean:indra
npm run test:sim:clean
npm run test:sim
```

### CODE REVIEW

**Comment by erkarl** [comment]
This PR needs additional fixes for making it work with the new connext version:
```
2020/08/24 13:51:52 Connext node reachability failure: Get http://172.17.0.1:8080: dial tcp 172.17.0.1:8080: connect: connection refused
```

**Comment by erkarl** [comment]
> This PR needs additional fixes for making it work with the new connext version:
> 
> ```
> 2020/08/24 13:51:52 Connext node reachability failure: Get http://172.17.0.1:8080: dial tcp 172.17.0.1:8080: connect: connection refused
> ```

The port for the node in dev mode had changed from 8080 to 8888. In addition, `LEGACY_MODE=true` environment flag for the client was needed.

**Comment by erkarl** [comment]
I'm now consistently getting another error locally. The source of the error is actual balance mismatch before and after channel opening for Alice.

```
    --- FAIL: TestIntegration/order_matching_and_swap_connext (17.74s)
        tests-integration.go:410:
                Error Trace:    tests-integration.go:410
                                                        harnessTest.go:95
                                                        xud_test.go:85
                Error:          Not equal:
                                expected: 0xbebb9cc
                                actual  : 0xbebb83c
                Test:           TestIntegration/order_matching_and_swap_connext
```

https://github.com/ExchangeUnion/xud/blob/feat/connext-simtest-7.3.6/test/simulation/tests-integration.go#L410

**Comment by sangaman** [comment]
My test failed due to a different reason after following the steps above:

```
Building connext
Step 1/7 : FROM node:12-alpine3.11
 ---> 18f4bc975732
Step 2/7 : RUN apk add --no-cache git bash python3 make g++ python
 ---> Using cache
 ---> e9a0a23d61fd
Step 3/7 : WORKDIR /app
 ---> Using cache
 ---> fcadb726d9f5
Step 4/7 : RUN git clone https://github.com/connext/rest-api-client.git
 ---> Using cache
 ---> a3c6d569d210
Step 5/7 : RUN cd rest-api-client && git pull
 ---> Using cache
 ---> 7c768c756b6d
Step 6/7 : RUN cd rest-api-client && git checkout 9dafbfb914415f70a14123de9e295df175633c24
 ---> Running in eb68d54a3e50
fatal: reference is not a tree: 9dafbfb914415f70a14123de9e295df175633c24
ERROR: Service 'connext' failed to build: The command '/bin/sh -c cd rest-api-client && git checkout 9dafbfb914415f70a14123de9e295df175633c24' returned a non-zero code: 128
```

**Comment by erkarl** [comment]
> ERROR: Service 'connext' failed to build: The command '/bin/sh -c cd rest-api-client && git checkout 9dafbfb914415f70a14123de9e295df175633c24' returned a non-zero code: 128

Do you get this consistently?
`ERROR: Service 'connext' failed to build: The command '/bin/sh -c cd rest-api-client && git checkout 9dafbfb914415f70a14123de9e295df175633c24' returned a non-zero code: 128` could be a network related error while it tried to clone the rest-api-client repository.

**Comment by erkarl** [comment]
The CI run also seems to be consistent with my local results: https://github.com/ExchangeUnion/xud/pull/1833/checks?check_run_id=1022428172

**Comment by erkarl** [comment]
The deposit call of the new client new returns a transaction hash immediately: https://github.com/connext/rest-api-client/blob/master/src/client.ts#L255

This was causing the test to assert the channel balance before the required 1 confirmation. I've also added additional 15 second timeout before attempting a swap so that the request for collateral request after a successful deposit has time to confirm.

**Comment by sangaman** [comment]
> > ERROR: Service 'connext' failed to build: The command '/bin/sh -c cd rest-api-client && git checkout 9dafbfb914415f70a14123de9e295df175633c24' returned a non-zero code: 128
> 
> Do you get this consistently?
> `ERROR: Service 'connext' failed to build: The command '/bin/sh -c cd rest-api-client && git checkout 9dafbfb914415f70a14123de9e295df175633c24' returned a non-zero code: 128` could be a network related error while it tried to clone the rest-api-client repository.

No I had only tried it once, but I don't think I was experiencing any network issues at the time. I suppose it could have been a GitHub issue as well. I'll try it again later.

**Comment by erkarl** [comment]
> I'll try it again later.

Thanks. The tests are now passing for me locally:
```
PASS
ok      github.com/ExchangeUnion/xud-simulation 984.445s
~/xud/test/simulation/temp/indra ~/xud/test/simulation
```

Let's see what the CI does.

**Comment by sangaman** [comment]
I got `fatal: reference is not a tree: 9dafbfb914415f70a14123de9e295df175633c24` again trying to test this branch, any other ideas I should try?

**Review by sangaman — DISMISSED** [review]
Tests are now passing for me locally as well, can you cleanup the commit history and merge?

**Pull request merged**
