### PR TITLE
feat: exposes lnduris & connextIdentifier on listpeers grpc call (#2017)

### LINKED ISSUE #2017: Expose lnuri, connexturi, connextchanneladdress on listpeers
Currently we only expose ln pubkeys, but not the full lnuri, nothing for connext:
```
Problem:
    {
      "address": "127.0.0.1:33870",
      "nodePubKey": "027178f1a99b1b39aeeb53192ad05f617963abba7731d1e7146302e779ed524608",
      "lndPubKeysMap": [
        [
          "BTC",
          "03e2496e71b524a3144aa4897487823803f1cc8a74ff7d912a331f4d5a9e1e6bf0"
        ],
        [
          "LTC",
          "03269a47ebba056ba66a6dcee35d5366bbdf845a13f2cef2ef205f6c2fbcfaad83"
        ]
      ],
      "inbound": true,
      "pairsList": [
        "ETH/BTC",
        "LTC/BTC",
        "LTC/USDT",
        "BTC/USDT",
        "USDT/DAI"
      ],
      "xudVersion": "1.2.2",
      "secondsConnected": 4127,
      "alias": "BulkSound"
    }
  ]
}
```

We want to expose the full lnuri, connexturi and additionally the connext "channel address" in `listpeers`. Depends on https://github.com/ExchangeUnion/xud/pull/1938

### PR DESCRIPTION
**Pull request by rsercano**
resolves #2017.

Currently only exposes `connext_identifier` for connext as @erkarl mentioned in the issue comment, but exposes LND uris. 

image

### CODE REVIEW

**Comment by kilrau** [comment]
In order to resolve #2017, we'd want to have lnd **URIs** too, I propose to separate the uri part from the pubkey into `address`, just like  we do with `xud` already, sth like this: 

```
    {
      "address": "127.0.0.1:33870",
      "nodePubKey": "027178f1a99b1b39aeeb53192ad05f617963abba7731d1e7146302e779ed524608",
      "lndUriMap": [
        [
          "BTC",
          "03e2496e71b524a3144aa4897487823803f1cc8a74ff7d912a331f4d5a9e1e6bf0",
          "127.0.0.1:33870"
        ],
        [
          "LTC",
          "03269a47ebba056ba66a6dcee35d5366bbdf845a13f2cef2ef205f6c2fbcfaad83",
          "127.0.0.1:33870"
        ]
      ],
     "connextUriMap": [
        [
          "03e2496e71b524a3144aa4897487823803f1cc8a74ff7d912a331f4d5a9e1e6bf0",
          "127.0.0.1:33870"
        ],
      "inbound": true,
      "pairsList": [
        "ETH/BTC",
        "LTC/BTC",
        "LTC/USDT",
        "BTC/USDT",
        "USDT/DAI"
      ],
      "xudVersion": "1.2.4",
      "secondsConnected": 4127,
      "alias": "BulkSound"
    }
  ]
}
```

**Comment by rsercano** [comment]
image
Current output with this PR

**Comment by rsercano** [comment]
> In order to resolve #2017, we'd want to have lnd **URIs** too, I propose to separate the uri part from the pubkey into `address`, just like we do with `xud` already, sth like this:
> 
> Wdyt? @erkarl @sangaman @raladev
> 
> ```
>     {
>       "address": "127.0.0.1:33870",
>       "nodePubKey": "027178f1a99b1b39aeeb53192ad05f617963abba7731d1e7146302e779ed524608",
>       "lndUriMap": [
>         [
>           "BTC",
>           "03e2496e71b524a3144aa4897487823803f1cc8a74ff7d912a331f4d5a9e1e6bf0",
>           "127.0.0.1:33870"
>         ],
>         [
>           "LTC",
>           "03269a47ebba056ba66a6dcee35d5366bbdf845a13f2cef2ef205f6c2fbcfaad83",
>           "127.0.0.1:33870"
>         ]
>       ],
>      "connextUriMap": [
>         [
>           "03e2496e71b524a3144aa4897487823803f1cc8a74ff7d912a331f4d5a9e1e6bf0",
>           "127.0.0.1:33870"
>         ],
>       "inbound": true,
>       "pairsList": [
>         "ETH/BTC",
>         "LTC/BTC",
>         "LTC/USDT",
>         "BTC/USDT",
>         "USDT/DAI"
>       ],
>       "xudVersion": "1.2.4",
>       "secondsConnected": 4127,
>       "alias": "BulkSound"
>     }
>   ]
> }
> ```

I phrased it wrong again edited my PR, I should think before writing 🤔

**Comment by kilrau** [comment]
> I phrased it wrong again, edited my PR, I should think before writing sorrythinking @kilrau

Ok, thx. Let's wait for @sangaman @erkarl to chime in and give an opinion on how the output should look like.

**Comment by erkarl** [comment]
For connext I'd call it for what it is `connextIdentifier` instead of `connextUriMap`. The type of it on p2p level can be string since there will only be one per peer.

**Comment by kilrau** [comment]
> For connext I'd call it for what it is `connextIdentifier` instead of `connextUriMap`. The type of it on p2p level can be string since there will only be one per peer.

How about the future when there will be more, connext allowing us to connect to different peers for different currencies? Shouldn't we try preparing for this?

**Comment by raladev** [comment]
> In order to resolve #2017, we'd want to have lnd **URIs** too, I propose to separate the uri part from the pubkey into `address`, just like we do with `xud` already, sth like this:
> 
> Wdyt? @erkarl @sangaman @raladev
> 
> ```
>     {
>       "address": "127.0.0.1:33870",
>       "nodePubKey": "027178f1a99b1b39aeeb53192ad05f617963abba7731d1e7146302e779ed524608",
>       "lndUriMap": [
>         [
>           "BTC",
>           "03e2496e71b524a3144aa4897487823803f1cc8a74ff7d912a331f4d5a9e1e6bf0",
>           "127.0.0.1:33870"
>         ],
>         [
>           "LTC",
>           "03269a47ebba056ba66a6dcee35d5366bbdf845a13f2cef2ef205f6c2fbcfaad83",
>           "127.0.0.1:33870"
>         ]
>       ],
>      "connextUriMap": [
>         [
>           "03e2496e71b524a3144aa4897487823803f1cc8a74ff7d912a331f4d5a9e1e6bf0",
>           "127.0.0.1:33870"
>         ],
>       "inbound": true,
>       "pairsList": [
>         "ETH/BTC",
>         "LTC/BTC",
>         "LTC/USDT",
>         "BTC/USDT",
>         "USDT/DAI"
>       ],
>       "xudVersion": "1.2.4",
>       "secondsConnected": 4127,
>       "alias": "BulkSound"
>     }
>   ]
> }
> ```
not sure why we need divide address and pubkey. I dont see cases when i need only address or only pubkey of the peer. Are they exsist?

**Comment by sangaman** [comment]
> For connext I'd call it for what it is `connextIdentifier` instead of `connextUriMap`. The type of it on p2p level can be string since there will only be one per peer.

Agree, `connextIdentifier` seems like all we need.

> not sure why we need divide address and pubkey. I dont see cases when i need only address or only pubkey of the peer. Are they exsist?

I agree as well, I think just one `lndUri` field (per currency) will do, and I personally think it's a bit excessive to return every lnd listening address. I would just return the first listening address and return it string format, `[pubkey]@[ipaddress/hostname]:[port]`, which in my experience is commonly used when connecting to new nodes/peers in lnd.

As an aside, what is the value in exposing the lnd uri at all? I see that's in the issue but I don't know what the use case is.

**Comment by michael1011** [comment]
> not sure why we need divide address and pubkey. I dont see cases when i need only address or only pubkey of the peer. Are they exsist?

For example you could build an application for the XUD API that queries the public channels of the LND node of the counterparty to check whether you can easily route before taking on order of them. But you could easily split a `[pubkey]@[ipaddress/hostname]:[port]` by `@` so that's not really a dealbreaker.

@sangaman @rsercano which LND URI are we showing when the LND node has more than one?

**Comment by rsercano** [comment]
> > not sure why we need divide address and pubkey. I dont see cases when i need only address or only pubkey of the peer. Are they exsist?
> 
> For example you could build an application for the XUD API that queries the public channels of the LND node of the counterparty to check whether you can easily route before taking on order of them. But you could easily split a `[pubkey]@[ipaddress/hostname]:[port]` by `@` so that's not really a dealbreaker.
> 
> @sangaman @rsercano which LND URI are we showing when the LND node has more than one?

Within this PR we're showing all lnd uris saved in the peer, so not selecting a particular one, but showing all.

**Comment by kilrau** [comment]
> not sure why we need divide address and pubkey. I dont see cases when i need only address or only pubkey of the peer. Are they exsist?

There might be, but even then it will be easy to split the pubkey part since the separator is always a `@`, I just proposed this for consistency but any way is fine!

Can you give this another spin? @raladev

**Review by raladev — CHANGES_REQUESTED** [review]
- [ ] @rsercano can u please rebase this branch to get vector changes from master?

- [ ] @erkarl @rsercano  Should connextIdentifier be empty for now?

```
      "lndUrisList": [
        {
          "currency": "BTC",
          "uriList": [
            "0252f366111259996a101c5a82c880e9c95c8278d7e668c40163c0db656161cbbf@b3y7xoflerllrmzharns7xqvke6w752nhe6dofvspsoxzay7pfa3ehyd.onion:29735"
          ]
        },
        {
          "currency": "LTC",
          "uriList": [
            "0252f366111259996a101c5a82c880e9c95c8278d7e668c40163c0db656161cbbf@vtovoe5sgr4lmutewqvzq3lx3z5a3tnmmnte6m5kiczlm2ykff247nyd.onion:30735"
          ]
        }
      ],
      "connextIdentifier": ""
```

**Comment by rsercano** [comment]
@raladev rebased

**Comment by erkarl** [comment]
> @erkarl @rsercano Should connextIdentifier be empty for now?

No. It should be the connext public identifier (something like `vector123abc...`)

**Comment by raladev** [comment]
> > @erkarl @rsercano Should connextIdentifier be empty for now?
> 
> No. It should be the connext public identifier (something like `vector123abc...`)

checked rebased version, connextIdentifier is still empty @rsercano 
Screenshot from 2020-12-08 16-32-03

**Comment by sangaman** [comment]
> > @sangaman @rsercano which LND URI are we showing when the LND node has more than one?
> 
> Within this PR we're showing all lnd uris saved in the peer, so not selecting a particular one, but showing all.

That part still excessive to me. Most nodes only expose one address anyway (my lnd node has 20 peers and none with more than 1 address) and I think in the case where they have more than one, any address should do. But I still don't really get the point of exposing the lnd listening uri through xud, so maybe I'm missing something. What do we expect the user to do with the lnd address(es) for peers? They are already connected so it's not like they can connect again, right?

**Comment by michael1011** [comment]
My personal, the Boltz ones and many routing nodes have two URIs: clearnet and Tor. So if we show the addresses, we should show all of them. Just in case.

But I don't recall the reason for showing them at all either. When you have the pubkey you can query the URIs from LND directly.

@rsercano sorry for all the back and forth. We should have agreed on that beforehand.

**Comment by rsercano** [comment]
> My personal, the Boltz ones and many routing nodes have two URIs: clearnet and Tor. So if we show the addresses, we should show all of them. Just in case.
> 
> But I don't recall the reason for showing them at all either. When you have the pubkey you can query the URIs from LND directly.
> 
> @rsercano sorry for all the back and forth. We should have agreed on that beforehand.

Yes of course it would be better and easier for me to continue if we all agree on same thing, no worries

**Comment by sangaman** [comment]
michael and I both are of the opinion that only exposing the lnd node pubkey, without any uris, makes most sense, which is the current behavior. The nodekey can be used to query lnd for more information about a node if it is needed. @kilrau Did you have a specific use case in mind for exposing the lnd uri(s)? We would presumably already be connected to the peer on the lnd layer.

**Comment by erkarl** [comment]
> michael and I both are of the opinion that only exposing the lnd node pubkey, without any uris, makes most sense, which is the current behavior. The nodekey can be used to query lnd for more information about a node if it is needed. @kilrau Did you have a specific use case in mind for exposing the lnd uri(s)? We would presumably already be connected to the peer on the lnd layer.

Think we're currently using the lnd uri for `openchannel` command (to connect to lnd if not already connected). I'd be fine with switching it to nodekey if we can query the uris on lnd level.

**Comment by erkarl** [comment]
Needs a rebase due to https://github.com/ExchangeUnion/xud/pull/2033 being merged.

**Comment by rsercano** [comment]
> Needs a rebase due to #2033 being merged.

done @erkarl

**Comment by erkarl** [comment]
> > Needs a rebase due to #2033 being merged.
> 
> done @erkarl

The build is failing after rebase.

**Comment by rsercano** [comment]
Have we implemented prettier already @erkarl 😅 Let me check

**Comment by rsercano** [comment]
Should be fixed now hopefully 😅 @erkarl 

On the other hand, I just exposed connextIdentifier stated in the peer's info, and added LND uris additionally and exposed them too.

**Review by raladev — CHANGES_REQUESTED** [review]
- [ ] checked i still have no connext identifier in listpeers response
Screenshot from 2020-12-09 15-02-09
Screenshot from 2020-12-09 15-00-49
Screenshot from 2020-12-09 15-00-06

**Comment by rsercano** [comment]
@raladev sorry Roman I managed to overlook same issue twice but should be fixed now. Unfortunately I can't test connextIdentifier myself, my connext somehow keeps throwing 500 🤔

**Comment by kilrau** [comment]
> The nodekey can be used to query lnd for more information about a node if it is needed. @kilrau Did you have a specific use case in mind for exposing the lnd uri(s)? We would presumably already be connected to the peer on the lnd layer.

Sorry that I missed answering here - yes it's for opening a channel to send funds from **another node**, which will be the setup for our upcoming xuc rewards.

Also, I think this is ready to be reviewed again. @sangaman

**Review by raladev — APPROVED** [review]

**Review by erkarl — COMMENTED** [review]
utACK

**Comment by kilrau** [comment]
Sry but we are requiring all commits to be signed @rsercano , could you pls force push a signed commit?

PS: `git config --global commit.gpgsign true`

**Comment by rsercano** [comment]
Hi @kilrau it took me some time to figure out but I already signed all my commits for this one, github was somehow unverified my email address, I re verified and now seems okay, can you please squash and merge instead of me? I literally suck at it since there're some in between commits, and I don't want to mess with them.

Let me know if you want me to create a new "clean" PR if squashing is not possible on your end. @sangaman @raladev

**Comment by erkarl** [comment]
> I literally suck at it since there're some in between commits, and I don't want to mess with them.

Something to try in the future:
```
git checkout master
// get latest from master
git pull origin master
// go back to your feature branch
git checkout feat/expose-lnd/connext-ids-listpeers
// rebase your branch against master
git rebase master
// go back X commits to rebase
git rebase -i HEAD~X
// choose the commits that you want to squash
// and edit the commit message
// push latest changes with force since the tree has divereged
git push origin feat/expose-lnd/connext-ids-listpeers -f
```

If you run into super complicated merge conflicts then you could also try to create a new branch based on master and `git cherry-pick` the commits that you do want to push.

**Comment by rsercano** [comment]
> > I literally suck at it since there're some in between commits, and I don't want to mess with them.
> 
> Something to try in the future:
> 
> ```
> git checkout master
> // get latest from master
> git pull origin master
> // go back to your feature branch
> git checkout feat/expose-lnd/connext-ids-listpeers
> // rebase your branch against master
> git rebase master
> // go back X commits to rebase
> git rebase -i HEAD~X
> // choose the commits that you want to squash
> // and edit the commit message
> // push latest changes with force since the tree has divereged
> git push origin feat/expose-lnd/connext-ids-listpeers -f
> ```
> 
> If you run into super complicated merge conflicts then you could also try to create a new branch based on master and `git cherry-pick` the commits that you do want to push.

I literally tried this a hundred times but resolving conflicts, not touching other commits, this's literally a mess for me 😢

**Comment by erkarl** [comment]
It's fine we can squash and merge before merging once it is ready to merge.

**Pull request merged**
