### PR TITLE
feat(swaps): increase swap timeout to 90 seconds

### LINKED ISSUE #1752: Increase swap timeout to 90s
Reason: connext live collateralization will cause failures otherwise (need 60-80s in total).

### PR DESCRIPTION
**Pull request by ghost**
Closes https://github.com/ExchangeUnion/xud/issues/1752

This PR increases taker's swap timeout to 90 seconds and maker's to 95 seconds.

### CODE REVIEW

**Review by sangaman — APPROVED** [review]

**Comment by kilrau** [comment]
Could you check simtests?

**Comment by raladev** [comment]
1. i got first swap timeout after 14:58:23.962 -  14:57:46.241 = 37 seconds (check maker's xud log at  14:58:23.962)
2. It seems connext has swap timeout too and we need to increase it too (check maker's connext log at 14:58:50.65)
3. taker xud was crushed during testing
4. Why TimeOut is dispalyed as UnknownErr?
5. both xud are using this branch - [Screenshot from 2020-07-24 18-08-56](https://user-images.githubusercontent.com/29906866/88407844-5ffa6a00-cddb-11ea-9a18-1842c6b9b77e.png)


Steps:
1. place ETH/BTC 8 orders as a maker
2. fill them as a taker

Result:
1. 1 successful swap for 0.8 qty (but i expected that 0.1 should be first)
2. Unknown err for other swaps (connext timeout)
3. taker's xud crush

[connext_maker_crush.log](https://github.com/ExchangeUnion/xud/files/4972776/connext_maker_crush.log)
[xud_maker_crush.log](https://github.com/ExchangeUnion/xud/files/4972777/xud_maker_crush.log)
[connext_taker_crush.log](https://github.com/ExchangeUnion/xud/files/4972778/connext_taker_crush.log)
[xud_taker_crush.log](https://github.com/ExchangeUnion/xud/files/4972779/xud_taker_crush.log)

**Comment by erkarl** [comment]
>     1. i got first swap timeout after 14:58:23.962 -  14:57:46.241 = 37 seconds (check maker's xud log at  14:58:23.962)
> 
>     2. It seems connext has swap timeout too and we need to increase it too (check maker's connext log at 14:58:50.65)
> 
>     3. taker xud was crushed during testing
> 
>     4. Why TimeOut is dispalyed as UnknownErr?
> 
>     5. both xud are using this branch - [Screenshot from 2020-07-24 18-08-56](https://user-images.githubusercontent.com/29906866/88407844-5ffa6a00-cddb-11ea-9a18-1842c6b9b77e.png)
> 
> 
> Steps:
> 
>     1. place ETH/BTC 8 orders as a maker
> 
>     2. fill them as a taker by one order
> 
> 
> Result:
> 
>     1. 1 successful swap for 0.8 qty (but i expected that 0.1 should be first)
> 
>     2. Unknown err for other swaps (connext timeout)
> 
>     3. taker's xud crush
> 
> 
> [connext_maker_crush.log](https://github.com/ExchangeUnion/xud/files/4972776/connext_maker_crush.log)
> [xud_maker_crush.log](https://github.com/ExchangeUnion/xud/files/4972777/xud_maker_crush.log)
> [connext_taker_crush.log](https://github.com/ExchangeUnion/xud/files/4972778/connext_taker_crush.log)
> [xud_taker_crush.log](https://github.com/ExchangeUnion/xud/files/4972779/xud_taker_crush.log)

Thanks for testing. You're right, this needs some more work.

**Comment by erkarl** [comment]
@raladev can you give it another run please?

**Comment by raladev** [comment]
1. No xud crush
2. Connext 60 timeout still exists (check multi_2_xud_maker.log) that displayed as Unknown Error
3. if connext timeout is not reproduced, xud's 90 sec SwapTimeout works fine (second group of logs) (27/07/2020 13:09:28.796 - 27/07/2020 13:07:57.274)

First group:

[multi_2_connext_maker.log](https://github.com/ExchangeUnion/xud/files/4982235/multi_2_connext_maker.log)
[multi_2_connext_taker.log](https://github.com/ExchangeUnion/xud/files/4982237/multi_2_connext_taker.log)
[multi_2_xud_maker.log](https://github.com/ExchangeUnion/xud/files/4982238/multi_2_xud_maker.log)
[multi_2_xud_taker.log](https://github.com/ExchangeUnion/xud/files/4982239/multi_2_xud_taker.log)


Second group:

[multi_2_connext_taker_correct_timeout.log](https://github.com/ExchangeUnion/xud/files/4982241/multi_2_connext_taker_correct_timeout.log)
[multi_2_connext_maker_correct_timeout.log](https://github.com/ExchangeUnion/xud/files/4982242/multi_2_connext_maker_correct_timeout.log)
[multi_2_xud_maker_correct_timeout.log](https://github.com/ExchangeUnion/xud/files/4982244/multi_2_xud_maker_correct_timeout.log)
[multi_2_xud_taker_correct_timeout.log](https://github.com/ExchangeUnion/xud/files/4982245/multi_2_xud_taker_correct_timeout.log)

**Comment by kilrau** [comment]
That's the "Connext 60 timeout" roman mentioned:
 ```
[1595854716617] ERROR (70 on connext): Evt timeout after 60000ms
    Error: Evt timeout after 60000ms
        at new Timeout (/app/node_modules/evt/lib/types/EvtError.js:23:34)
        at Timeout._onTimeout (/app/node_modules/evt/lib/Evt.js:186:26)
        at listOnTimeout (internal/timers.js:549:17)
        at processTimers (internal/timers.js:492:7)
```

That a generic 60s timeout for events? Weird that it disappeared and timeouts worked as expected after trying again.

**Pull request merged**
