### PR TITLE
Connext fixes

### LINKED ISSUE #1517: xucli getinfo returns nothing because of socket hang up error for connext node
### Background

xucli getinfo returns nothing because of socket hang up error for connext node. **It seems i should get socket hang up error in connext status cell of getinfo request**, but i got nothing instead. its just not good to block access to lnd info when connext does not work. 

Note: same behaviour for status command in docker-env

### Logs

[f_connext.log](https://github.com/ExchangeUnion/xud/files/4557746/f_connext.log)
[f_utils.log](https://github.com/ExchangeUnion/xud/files/4557747/f_utils.log)
[f_xud.log](https://github.com/ExchangeUnion/xud/files/4557748/f_xud.log)

### Screen

Screenshot 2020-04-30 13:07:02

### PR DESCRIPTION
**Pull request by ghost**
Built on top of: https://github.com/ExchangeUnion/xud/pull/1508

Fixes: #1517

### CODE REVIEW

**Comment by kilrau** [comment]
Can we also remote this raiden error?
```
General XUD Info
┌───────────────┬───────────────────────────────────────────────────────────────────────┐
│ Status        │ LND-LTC: lnd-LTC has no active channels                               │
│               │ Raiden: Could not fetch status informatio                             │
├───────────────┼───────────────────────────────────────────────────────────────────────┤
```

**Comment by kilrau** [comment]
And the channel info here and network should be `connext simnet`
```
Connext info:
┌──────────┬────────────────────────────────────────────┐
│ Status   │ Ready                                      │
├──────────┼────────────────────────────────────────────┤
│ Version  │ 6.1.0                                      │
├──────────┼────────────────────────────────────────────┤
│ Address  │ 0x1698D705579f928082A29C9cF54278E8EE1c53FF │
├──────────┼────────────────────────────────────────────┤
│ Channels │ Active: 1 | Pending: 0 | Closed: 0         │
├──────────┼────────────────────────────────────────────┤
│ Network  │  simnet                                    │
└──────────┴────────────────────────────────────────────┘ 
```

**Comment by erkarl** [comment]
> And the channel info here and network should be `connext simnet`
> Can we also remove this raiden error?

Done.

**Comment by kilrau** [comment]
I'm aware the connext child seed is derived after, but still it  is connected to this seed, so we somehow have to add `ETH` here:

```
----------------------BEGIN XUD SEED---------------------
 1. ability     2. ranch       3. boring      4. kid       
 5. potato      6. miracle     7. praise      8. poverty   
 9. raven      10. gasp       11. gorilla    12. opinion   
13. swarm      14. evolve     15. sense      16. phone     
17. kitten     18. there      19. casual     20. window    
21. gesture    22. mechanic   23. soccer     24. ability   
-----------------------END XUD SEED----------------------

The following wallets were initialized: BTC, LTC
```

**Comment by kilrau** [comment]
Can you give this a review? @sangaman

**Comment by erkarl** [comment]
Also fixes: https://github.com/ExchangeUnion/xud/issues/1517

**Comment by kilrau** [comment]
> Also fixes: #1517

Added this to the PR description to make automation work.

**Review by sangaman — APPROVED** [review]
The code looks really good. My only question would be about removing raiden from the getinfo response. We are already not display raiden when raiden is disabled. Removing any logic to show it from the cli while it still is on the grpc response seems a little unusual to me, is there a reason for it I'm missing?

**Comment by erkarl** [comment]
> My only question would be about removing raiden from the getinfo response. We are already not display raiden when raiden is disabled. Removing any logic to show it from the cli while it still is on the grpc response seems a little unusual to me, is there a reason for it I'm missing?

Good point. I'll do all raiden related cleanup in https://github.com/ExchangeUnion/xud/issues/1516

**Pull request merged**
