### PR TITLE
refactor(rpc): rename reserved TradingLimits fields

### PR DESCRIPTION
**Pull request by sangaman**
This renames the `reservedOutbound` and `reservedInbound` fields on the `TradingLimits` call to `reservedSell` and `reservedBuy` respectively.

This is take two for #1946, which was reverted shortly after being merged to prevent conflicts with xud-ui. Whenever the ui project is ready for these new names we should merge this for good.

### CODE REVIEW

**Comment by kilrau** [comment]
Nice - let's get it in with the next release then!

**Comment by raladev** [comment]
we already have identical PR for that - https://github.com/ExchangeUnion/xud/pull/1954 )

**Comment by kilrau** [comment]
> we already have identical PR for that - #1954 )

True, closing here.

**Review by krrprr — APPROVED** [review]

**Review by raladev — APPROVED** [review]

**Review by erkarl — APPROVED** [review]

**Comment by erkarl** [comment]
Thanks @sangaman

**Pull request merged**
