### PR TITLE
feat(database): enable WETH trading pair and currency by default

### PR DESCRIPTION
**Pull request by ghost**
In this PR we're modifying the initial database bootstrapping code
to include `WETH` currency by default along with `WETH/BTC` trading
pair.

As a default Rinkeby testnet contract address is used (until we get
support for network specific database/schema).

### CODE REVIEW

**Review by sangaman — APPROVED** [review]

**Comment by sangaman** [comment]
Super minor note, in the past I've written the commit message as `feat(db)` instead of writing out database makes the commit message a bit shorter. Change if you so please.

**Comment by erkarl** [comment]
Updated the commit message.

**Comment by erkarl** [comment]
Going to close this because after discussing it with @offerm and @sangaman we felt like `xud-simnet` script would be better place to add this. The contract address for simnet is subject to change and we don't want to have a hardcoded value in the xud internals.

**Comment by kilrau** [comment]
Makes sense, but maybe prepare the testnet and mainnet defaults? (I guess it makes sense to wait for https://github.com/ExchangeUnion/xud/pull/827)

If lnd is enabled = LTC/BTC
If lnd+raiden is enabled = LTC/BTC, WETH/BTC, LTC/WETH

**Comment by erkarl** [comment]
Created: https://github.com/ExchangeUnion/xud/issues/872

**Pull request closed without merging**
