### PR TITLE
Upgrade lnd to 0.8.2

### PR DESCRIPTION
**Pull request by ghost**
This PR upgrades our simulation test lnd to `0.8.2` and updated the proto definitions.

@sangaman do we still need the `jstype = JS_STRING` definitions? IIRC, those were only needed for the `SendToRoute` to function properly, but we're no longer using it.

### CODE REVIEW

**Review by sangaman — COMMENTED** [review]
We don't need to manually add the `jstype` properties since we're not using channel ids in any lnd calls such as `SendToRoute`. The code and the travis runs look good, however locally this keeps failing for me with the error below and I can't figure out why. Any ideas?

```
=== RUN   TestIntegration/raiden_swap

waiting for raidens to boot...

raiden address found for Bob: 0x0711f7Da3A8AF222c5872Dca134678Ea2aC4ef7b

raiden address found for Alice: 0x418e59bdDb4a8982f99dbd71Fab66f5DB13c2cce

waiting for raiden channel to become active...
2019/12/17 23:38:25 lnd-btc: network harness teared down
2019/12/17 23:38:25 btcd: harness teared down
2019/12/17 23:38:25 lnd-ltc: network harness teared down
2019/12/17 23:38:25 ltcd: harness teared down
2019/12/17 23:38:36 xud process (2-Bob) did not shutdown gracefully. process (20268) killed
2019/12/17 23:38:36 xud network harness teared down
2019/12/17 23:38:36 cleaning up processes...
2019/12/17 23:38:36 cleanup complete
--- FAIL: TestIntegration (182.22s)
    xud_test.go:70: Running 9 integration tests
    --- PASS: TestIntegration/network_initialization (0.79s)
    --- FAIL: TestIntegration/raiden_swap (142.14s)
        actions.go:238: 
            	Error Trace:	actions.go:238
            	            				tests-integration.go:271
            	            				harnessTest.go:93
            	            				xud_test.go:94
            	Error:      	"[order_id:"272bbea0-2150-11ea-9cb9-45f4dfc30ea7" pair_id:"WETH/BTC" quantity:10000 peer_pub_key:"03069b629c922af6f4766082a71ecf3c7491a779eab547105054bbd67c3073f307" failure_reason:"SwapTimedOut" ]" should have 0 item(s), but has 1
            	Test:       	TestIntegration/raiden_swap
FAIL
exit status 1
```

**Comment by erkarl** [comment]
> We don't need to manually add the `jstype` properties since we're not using channel ids in any lnd calls such as `SendToRoute`. The code and the travis runs look good, however locally this keeps failing for me with the error below and I can't figure out why. Any ideas?
> 
> ```
> === RUN   TestIntegration/raiden_swap
> 
> waiting for raidens to boot...
> 
> raiden address found for Bob: 0x0711f7Da3A8AF222c5872Dca134678Ea2aC4ef7b
> 
> raiden address found for Alice: 0x418e59bdDb4a8982f99dbd71Fab66f5DB13c2cce
> 
> waiting for raiden channel to become active...
> 2019/12/17 23:38:25 lnd-btc: network harness teared down
> 2019/12/17 23:38:25 btcd: harness teared down
> 2019/12/17 23:38:25 lnd-ltc: network harness teared down
> 2019/12/17 23:38:25 ltcd: harness teared down
> 2019/12/17 23:38:36 xud process (2-Bob) did not shutdown gracefully. process (20268) killed
> 2019/12/17 23:38:36 xud network harness teared down
> 2019/12/17 23:38:36 cleaning up processes...
> 2019/12/17 23:38:36 cleanup complete
> --- FAIL: TestIntegration (182.22s)
>     xud_test.go:70: Running 9 integration tests
>     --- PASS: TestIntegration/network_initialization (0.79s)
>     --- FAIL: TestIntegration/raiden_swap (142.14s)
>         actions.go:238: 
>             	Error Trace:	actions.go:238
>             	            				tests-integration.go:271
>             	            				harnessTest.go:93
>             	            				xud_test.go:94
>             	Error:      	"[order_id:"272bbea0-2150-11ea-9cb9-45f4dfc30ea7" pair_id:"WETH/BTC" quantity:10000 peer_pub_key:"03069b629c922af6f4766082a71ecf3c7491a779eab547105054bbd67c3073f307" failure_reason:"SwapTimedOut" ]" should have 0 item(s), but has 1
>             	Test:       	TestIntegration/raiden_swap
> FAIL
> exit status 1
> ```

@sangaman I'm occasionally experiencing the same error. When I reduce/remove [this timeout](https://github.com/ExchangeUnion/xud/blob/master/test/simulation/tests-integration.go#L251) I can reproduce the problem 100% of the time.

Looks like the 90 seconds we're currently providing is not enough for your environment. Raiden nodes communicate via matrix servers and it takes time for the clients to join the room when a channel is established. Unfortunately, I have good way of verifying if both clients have joined the matrix room.

We could try running a local matrix server instead of using `https://raidentransport.exchangeunion.com`, but I'm not 100% sure it will work. Alternatively, we could try increasing the timeout (which is not ideal because it makes the test suite run longer).

**Comment by erkarl** [comment]
@sangaman I've increased the timeout from 90 to 180 seconds. Could you try running it locally again and see if you still get the same error?

**Review by sangaman — APPROVED** [review]
I got a pass on the second try after the new changes. I think a good approach instead of sleeping for 180 seconds might be to sleep ~10 seconds at a time (maybe a slightly longer wait up front) and then try a swap. If it fails, wait more and try again, up to an even higher limit so we get fewer fails (maybe 300 seconds). We can try that in a separate PR tho.

**Comment by kilrau** [comment]
I ran it 3x with go1.12 and 3x with go1.13. All failed with:
```
Waiting for blocks to be mined (current: 1161, target 1299)...
Target height 1299 reached. Generated 500 blocks.
TokenNetworkRegistry is 0x2207Eef0A88224dBDc8774DD4B0bf96EC5D65DFd
SecretRegistry is 0x690B4d0EdA40F342bb35B6F8Ea5553D34Af73c11
OneToN is 0xa349d6Cf4A0CA6551668dEe535ba4Fc53ECD8Baa
UserDeposit is 0x6CC11Fb758EFca26B2D288DCdfd480c15Ce994f5
MonitoringService is 0x3C1a1c9B384e0D1B9694187E0b7D8B1F8779B7BF
exit status 1
FAIL	github.com/ExchangeUnion/xud-simulation	296.003s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xud@1.0.0-mainnet test:sim: `(npm run compile:dev && cd test/simulation && export PATH="$PWD/go/bin:$PATH" && GOPATH=$PWD/go GO111MODULE=on go test -timeout 30m -run=TestIntegration -v)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xud@1.0.0-mainnet test:sim script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kilrau/.npm/_logs/2019-12-18T18_57_36_154Z-debug.log
```

**Comment by erkarl** [comment]
> I got a pass on the second try after the new changes. I think a good approach instead of sleeping for 180 seconds might be to sleep ~10 seconds at a time (maybe a slightly longer wait up front) and then try a swap. If it fails, wait more and try again, up to an even higher limit so we get fewer fails (maybe 300 seconds). We can try that in a separate PR tho.

Thanks. I really like this approach. Created https://github.com/ExchangeUnion/xud/issues/1354

**Pull request merged**
