### PR TITLE
feat: peer order match events & alias

### LINKED ISSUE #1514: Print peer order match (and more)
## How it is:
In case of own order matches, a `match` is printed:
```
matched 0.001 ETH @ 3 with own order 29e3eeb0-8a28-11ea-90cf-439fb244cf44
```
For peer orders not:
```
simnet > buy 1 ltc/btc 0.05
swapped 1 LTC with peer order 79d2cd30-8a26-11ea-90cf-439fb244cf44
```
Which is not consistent and not very good UX since between pressing enter and the result up to 45 seconds can pass without the trader knowing what's going on under the hood.

## How it should be:
```
simnet > buy 1 ltc/btc 0.05
matched 1 LTC @ 0.05 with peer order 79d2cd30-8a26-11ea-90cf-439fb244cf44 (NodeAlias), attempting swap...
successfully swapped 1 LTC with peer order 79d2cd30-8a26-11ea-90cf-439fb244cf44 (NodeAlias)
```

How it should be (partial success, partial fail)
```
simnet > buy 1 ltc/btc 0.05
matched 0.5 LTC @ 0.05 with peer order 79d2cd30-8a26-11ea-90cf-439fb244cf44 (NodeAlias), attempting swap...
matched 0.5 LTC @ 0.05 with peer order 72166790-8a27-11ea-9b5f-0b3481cf9ca3 (NodeAlias), attempting swap...
successfully swapped 0.5 LTC with peer order 79d2cd30-8a26-11ea-90cf-439fb244cf44 (NodeAlias)
failed to swap with peer order 72166790-8a27-11ea-9b5f-0b3481cf9ca3 (NodeAlias)
remaining 0.5 LTC entered the order book as 66a79330-8a26-11ea-9b5f-0b3481cf9ca3
```

### PR DESCRIPTION
**Pull request by sangaman**
This enhances the details returned by the `PlaceOrder` call and output by the `placeorder` command to include events for when a peer order is matched and swapping routine begins as well as the alias of the peer whose order we matched with.

Closes #1514.

I still need to test this with some live swaps but was running into issues with Docker, so this could still use some more trial runs.

### CODE REVIEW

**Comment by raladev** [comment]
- [] No successful swap message in cli output
[Screenshot 2020-05-15 14:28:55](https://user-images.githubusercontent.com/29906866/82046637-edbe2880-96b9-11ea-9169-d1e23be5bd7f.png)
[Screenshot 2020-05-15 14:29:11](https://user-images.githubusercontent.com/29906866/82046678-01698f00-96ba-11ea-9f22-cb373b1c5669.png)
- [] Failed tests

**Comment by sangaman** [comment]
>     * [ ]  No successful swap message in cli output
>       [Screenshot 2020-05-15 14:28:55](https://user-images.githubusercontent.com/29906866/82046637-edbe2880-96b9-11ea-9169-d1e23be5bd7f.png)
>       [Screenshot 2020-05-15 14:29:11](https://user-images.githubusercontent.com/29906866/82046678-01698f00-96ba-11ea-9f22-cb373b1c5669.png)
> 
>     * [ ]  No peer in cli message (but exists in logs)
> 
>     * [ ]  Failed tests

Thanks for checking, I'll get some tests in today and let you know when to try again.

**Comment by kilrau** [comment]
> Thanks for checking, I'll get some tests in today and let you know when to try again.

I guess that's needed to get travis passing? Or do we have travis troubles?

**Comment by sangaman** [comment]
@raladev I just updated this branch, should be good for another shot now:

```bash
$ xucli buy 0.001 LTC/BTC mkt
matched 0.001 LTC @ 0.01 with peer OnionToilet order b38d9b80-98eb-11ea-9c49-ffe3e2eb3105, attempting swap...
successfully swapped 0.001 LTC with peer order b38d9b80-98eb-11ea-9c49-ffe3e2eb3105
```

> I guess that's needed to get travis passing? Or do we have travis troubles?

I just needed to update one of the import references in one of the tests, it should be good now.

**Pull request merged**
