### PR TITLE
feat: seed ports adjustment

### PR DESCRIPTION
**Pull request by reliveyy**
Related to https://github.com/ExchangeUnion/xud-docker/pull/167

### CODE REVIEW

**Comment by erkarl** [comment]
Think we also need to change our currently running simnet and testnet server ports, right?

```
[1] 18/09/2019 09:12:54.945 [P2P] info: Connecting to known / previously connected peers
[1] 18/09/2019 09:12:55.115 [P2P] warn: could not open connection to peer (028599d05b18c0c3f8028915a17d603416f7276c822b6b2d20e71a3502bd0f9e0a@xud2.simnet.exchangeunion.com:28885): could not connect to peer at xud2.simnet.exchangeunion.com:28885: connect ECONNREFUSED 35.231.171.148:28885
[1] 18/09/2019 09:12:55.121 [P2P] warn: could not open connection to peer (02b66438730d1fcdf4a4ae5d3d73e847a272f160fee2938e132b52cab0a0d9cfc6@xud1.simnet.exchangeunion.com:28885): could not connect to peer at xud1.simnet.exchangeunion.com:28885: connect ECONNREFUSED 35.196.118.79:28885
[1] 18/09/2019 09:12:55.147 [P2P] warn: could not open connection to peer (03fd337659e99e628d0487e4f87acf93e353db06f754dccc402f2de1b857a319d0@xud3.simnet.exchangeunion.com:28885): could not connect to peer at xud3.simnet.exchangeunion.com:28885: connect ECONNREFUSED 35.229.81.83:28885
[1] 18/09/2019 09:12:55.147 [P2P] info: Completed start-up connections to known peers
```

**Comment by reliveyy** [comment]
> Think we also need to change our currently running simnet and testnet server ports, right?

Yes.

**Comment by sangaman** [comment]
Should we also change the default ports away from 8885/8886 depending on the active network? Or can that be left as is?

**Comment by kilrau** [comment]
> Should we also change the default ports away from 8885/8886 depending on the active network? Or can that be left as is?

Yes indeed we should and `xud.conf` should be created with these. If `xud` runs in Simnet Mode - 28885/28886, Testnet Mode 18885/18886, Mainnet stays with 8885/8886. Who can throw up a PR for this?

**Comment by sangaman** [comment]
> Yes indeed we should and `xud.conf` should be created with these. If `xud` runs in Simnet Mode - 28885/28886, Testnet Mode 18885/18886, Mainnet stays with 8885/8886. Who can throw up a PR for this?

I can do it, maybe 3888x for regtest? I don't think we're using it except in tests but I figure it makes sense for completeness sake.

**Comment by kilrau** [comment]
> I can do it, maybe 3888x for regtest? I don't think we're using it except in tests but I figure it makes sense for completeness sake.

Yes!

**Pull request merged**
