### PR TITLE
refactor: remove detectexternalip

### LINKED ISSUE #1092: Remove `detectexternalip`
this is handled by docker now and code and config option should be removed from xud

### PR DESCRIPTION
**Pull request by michael1011**
Closes #1092 

I removed the feature itself and all mentions of it from the code. This involved changing some error codes which is fine I think because I discovered that two distinct errors had the same code.

### CODE REVIEW

**Comment by sangaman** [comment]
As discussed in the issue I think we may want to keep this code, so I'll hold off on reviewing for now.

**Comment by kilrau** [comment]
Let's quickly discuss this in the call.

I tested this some days ago: enabled the feature via `xud.conf`, but it didnt' detect my ip/set it in the URI. No log entries. If it works, we can keep it.

**Comment by kilrau** [comment]
If somebody can confirm this is still working (it does not for me) and does NOT conflict with our TOR setup and manual setting URI's, we can close this PR and keep the feature.

**Comment by sangaman** [comment]
@kilrau I just confirmed that external ip detection works for me while not using tor. @erkarl would you have time to try running `xud` with `--p2p.detectexternalip` while using tor to make sure there are no issues?

**Comment by sangaman** [comment]
I am thinking however that even if this does cause issues with tor, we may still want to keep this logic and just add some checks to skip or gracefully fail the external ip detection procedure when we are using tor. So my inclination would be to close this PR.

**Comment by erkarl** [comment]
> So my inclination would be to close this PR.

Agreed.

**Pull request closed without merging**
