### PR TITLE
Ddtd framework

### PR DESCRIPTION
**Pull request by programarivm**
Here is a very basic DDTD setup in TypeScript (hello world setup :)

```
npm run test:ddtd

> xud@1.0.0-prealpha.1 test:ddtd /home/standard/projects/xud
> mocha -r ts-node/register test/ddtd/**/*



  http://localhost:8080/api/v1/info
    ✓ responds with http status 200



  1 passing (53ms)
```
Two conventions are implemented.

1. The `test/ddtd` subfolders are the API endpoints, as it is shown next:

- `test/ddtd/info`
- `test/ddtd/cancelorder`
- `test/ddtd/placeorder`
- `...`

2. The files are named as in the following example:

- `test/ddtd/placeorder/HttpStatus200.spec.ts`
- `test/ddtd/placeorder/HttpStatus400.spec.ts`
- `test/ddtd/placeorder/HttpStatus401.spec.ts`
- `test/ddtd/placeorder/HttpStatus404.spec.ts`
- `test/ddtd/placeorder/HttpStatus500.spec.ts`
- `...`

> Remember: the data is stored in json or csv files.

### CODE REVIEW

**Comment by programarivm** [comment]
http://localhost:8080/api/v1/placeorder seems to be failing

```
npm run test:ddtd

> xud@1.0.0-prealpha.1 test:ddtd /home/standard/projects/xud
> mocha -r ts-node/register test/ddtd/**/*



  http://localhost:8080/api/v1/info
    ✓ responds with http status 200

  http://localhost:8080/api/v1/placeorder
    1) responds with http status 200


  1 passing (2s)
  1 failing

  1) http://localhost:8080/api/v1/placeorder
       responds with http status 200:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```
This is consistent with the following:
```
curl -X POST -i http://localhost:8080/api/v1/placeorder --data '{ "pair_id": "BTC/LTC", "order_id": 1337, "price": 1, "quantity": 99 }'
```

**Comment by michael1011** [comment]
@programarivm that is because the webproxy is not enabled by default. We could either enable it by setting the config in the Travis build or by enabling it by default. @sangaman @moshababo

**Comment by programarivm** [comment]
@michael1011 Not very clear about that -- I am sorry, still getting familiar with the app. Mmmm. If that is the case, how is it that http://localhost:8080/api/v1/info passes? 

Btw, I am running `xud` as described next:
```
./xud --webproxy.disable false --lnd.disable true --raiden.disable true
```

**Comment by programarivm** [comment]
@michael1011 I see, that makes sense. It is as if the `placeorder` method is still on development, so we have to iterate through the TDD process in order to make the test pass.

This is the error being thrown:

```
Xud.PlaceOrder:  keyOrObj.hasOwnProperty is not a function
Trace
    at router.(anonymous function) (/home/standard/projects/xud/node_modules/@exchangeunion/grpc-dynamic-gateway/index.js:61:45)
    at Layer.handle [as handle_request] (/home/standard/projects/xud/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/standard/projects/xud/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/standard/projects/xud/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/standard/projects/xud/node_modules/express/lib/router/layer.js:95:5)
    at /home/standard/projects/xud/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/standard/projects/xud/node_modules/express/lib/router/index.js:335:12)
    at next (/home/standard/projects/xud/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/standard/projects/xud/node_modules/express/lib/router/index.js:174:3)
    at router (/home/standard/projects/xud/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/standard/projects/xud/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/standard/projects/xud/node_modules/express/lib/router/index.js:317:13)
    at /home/standard/projects/xud/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/standard/projects/xud/node_modules/express/lib/router/index.js:335:12)
    at next (/home/standard/projects/xud/node_modules/express/lib/router/index.js:275:10)
    at /home/standard/projects/xud/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/home/standard/projects/xud/node_modules/raw-body/index.js:224:16)
    at done (/home/standard/projects/xud/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/home/standard/projects/xud/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:180:13)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19) 
```

**Comment by programarivm** [comment]
http://localhost:8080/api/v1/cancelorder seems to be passing

```
npm run test:ddtd

> xud@1.0.0-prealpha.1 test:ddtd /home/standard/projects/xud
> mocha -r ts-node/register test/ddtd/suite.ts



  http://localhost:8080/api/v1/info
    ✓ responds with http status 200

  http://localhost:8080/api/v1/placeorder
    1) responds with http status 200

  http://localhost:8080/api/v1/cancelorder
    ✓ responds with http status 200


  2 passing (2s)
  1 failing

  1) http://localhost:8080/api/v1/placeorder
       responds with http status 200:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

```
Review why it is passing (HTTP Status 200) even though the order could not be placed successfully -- in this case, 404 Not Found or 400 Bad Request could be taken into consideration instead of 200.

**Comment by programarivm** [comment]
`client.getInfo()` seems to be failing when no params are used:

```
npm run test:ddtd

> xud@1.0.0-prealpha.1 test:ddtd /home/standard/projects/xud
> mocha -r ts-node/register test/ddtd/**/suite.ts


/home/standard/projects/xud/node_modules/ts-node/src/index.ts:330
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
test/ddtd/grpc/getInfo/GrpcStatus0.spec.ts (11,5): Expected 2-4 arguments, but got 0. (2554)
```

**Comment by programarivm** [comment]
At this moment, here is the output of the tests:

```
npm run test:ddtd

> xud@1.0.0-prealpha.1 test:ddtd /home/standard/projects/xud
> mocha -r ts-node/register test/ddtd/**/suite.ts



  client.getInfo()
    1) responds with grpc status 0

  client.cancelOrder()
    2) responds with grpc status 0

  http://localhost:8080/api/v1/info
    ✓ responds with http status 200 (64ms)

  http://localhost:8080/api/v1/placeorder
    3) responds with http status 200

  http://localhost:8080/api/v1/cancelorder
    ✓ responds with http status 200


  2 passing (2s)
  3 failing

  1) client.getInfo()
       responds with grpc status 0:
     AssertionError: TODO: expected false to be truthy
      at Context.it (test/ddtd/grpc/getInfo/GrpcStatus0.spec.ts:13:12)

  2) client.cancelOrder()
       responds with grpc status 0:
     AssertionError: TODO: expected false to be truthy
      at /home/standard/projects/xud/test/ddtd/grpc/cancelOrder/GrpcStatus0.spec.ts:31:14
      at Array.forEach (<anonymous>)
      at Context.it (test/ddtd/grpc/cancelOrder/GrpcStatus0.spec.ts:25:15)

  3) http://localhost:8080/api/v1/placeorder
       responds with http status 200:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

**Comment by sangaman** [comment]
Tests currently failing for me because the typescript won't compile:

```shell
test\ddtd\grpc\getInfo\GrpcStatus0.spec.ts (14,25): Object is possibly 'null'. (2531)
test\ddtd\grpc\getInfo\GrpcStatus0.spec.ts (14,34): Property 'toObject' does not exist on type 'Error'. (2339)
```

**Comment by programarivm** [comment]
Yep, this is because the tests are assuming the client is using a new game changer interface as discussed at https://github.com/ExchangeUnion/xud/issues/322

**Comment by sangaman** [comment]
Oh ok, well I'm not convinced we should be changing our grpc service in that way, but we can have the discussion in the issue. Ping me when these are ready to test.

**Comment by programarivm** [comment]
That sounds okay @sangaman and I just closed the issue. Thanks! I'll make these pass with the current interface asap -- please be a little patient, most probably next week I won't be able to commit very frequently.

**Comment by sangaman** [comment]
Thank you! Take your time.

**Comment by programarivm** [comment]
@sangaman, here are the results of the tests:

```
npm run test:ddtd

> xud@1.0.0-prealpha.1 test:ddtd /home/standard/projects/xud
> mocha -r ts-node/register test/ddtd/**/suite.ts



  client.getInfo()
    ✓ returns a response on success (53ms)

  client.placeOrder()
    1) returns a response on success

  client.cancelOrder()
    ✓ returns a response on success

  http://localhost:8080/api/v1/info
    ✓ responds with http status 200

  http://localhost:8080/api/v1/placeorder
    2) responds with http status 200

  http://localhost:8080/api/v1/cancelorder
    ✓ responds with http status 200


  4 passing (2s)
  2 failing

  1) client.placeOrder()
       returns a response on success:
     Error: 5 NOT_FOUND: invalid pairId: BTC/LTC
      at Object.exports.createStatusError (node_modules/grpc/src/common.js:87:15)
      at Object.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:1188:28)
      at InterceptingListener._callNext (node_modules/grpc/src/client_interceptors.js:564:42)
      at InterceptingListener.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:614:8)
      at callback (node_modules/grpc/src/client_interceptors.js:841:24)

  2) http://localhost:8080/api/v1/placeorder
       responds with http status 200:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```
With `http://localhost:8080/api/v1/placeorder` throwing this error:

`Xud.PlaceOrder:  .xudrpc.PlaceOrderRequest#pair_id is not a field: undefined`

**Comment by programarivm** [comment]
Regarding the grpc tests returning OK responses, note that they are named:

> returns a response on success

instead of

> responds with grpc status 0

As discussed at https://github.com/ExchangeUnion/xud/issues/322, the current grpc tests are not sticking with this convention:

- `GrpcStatus0.spec.ts`
- `GrpcStatus1.spec.ts`
- `...`

We still might have to define how the server responds with OK = 0.

**Comment by programarivm** [comment]
Hi @sangaman I hope this PR will make sense :)

Given:

https://github.com/programarivm/xud/blob/ddtd-framework/test/ddtd/grpc/executeSwap/GrpcStatus0.spec.ts

and:

https://github.com/programarivm/xud/blob/ddtd-framework/test/ddtd/grpc/executeSwap/data/grpc_status_0.json

How could three sample queries (grpc status code OK = 0) be simulated with sample data?

**Comment by sangaman** [comment]
@programarivm Any interest in picking this back up? A decent amount has changed but the api should be quite a bit more stable now than when this began. Thanks either way.

**Comment by programarivm** [comment]
@sangaman thanks for keeping me posted on the updates. I am definitely interested in testing the api and learn more on xud, just have to find some time and dedication.

**Comment by sangaman** [comment]
No worries, if you find the time at any point it would definitely be appreciated. Should we close this PR for now? You can always open a new one.

**Comment by programarivm** [comment]
Yes, that's okay for now. Thank you for your patience! Your feedback is also very helpful and I look forward to finding ways to contributing to ExchangeUnion on a more regular basis.

**Pull request closed without merging**
