### PR TITLE
aliases now have a third part for collision avoidance

### LINKED ISSUE #1688: Fix alias collisions
### Background

We are seeing alias collisions frequently https://github.com/ExchangeUnion/xud/issues/1687 , especially on travis. Since statistically this is extremely unlikely to happen, this issue is about finding and fixing the root cause of such.

### PR DESCRIPTION
**Pull request by hatmer**
closes #1688

### CODE REVIEW

**Comment by raladev** [comment]
Tested manually, works.
@kilrau @sangaman  What do you think about Number solution?
Screen

**Comment by hatmer** [comment]
If the extra number is bad then an alternative solution is to simply modify the wordlist file to be a set of 2048^2 aliases so that pubkeys can map directly to >4 million aliases. I probably should have tried this first, so I'll do this now.

**Comment by erkarl** [comment]
> If the extra number is bad then an alternative solution is to simply modify the wordlist file to be a set of 2048^2 aliases so that pubkeys can map directly to >4 million aliases. I probably should have tried this first, so I'll do this now.

Yeah, I think that's a better approach. Thoughts @kilrau @sangaman?

**Comment by sangaman** [comment]
I do think that adding a number to the alias makes it less memorable than just a couple of words. I'd rather we do a third word if necessary, or increase our word list size.

My bigger concern is whether this is necessary - have we actually seen collisions in the wild? I suspect the issue with travis alias collisions is not due to the birthday problem but rather due to some issue with pseudorandomness with tests that are running back to back or near simultaneously (as @raladev  said). The odds that we'd get collisions with just 1 or 2 peers - and that's all our tests are using I believe - is extremely low.

> an alternative solution is to simply modify the wordlist file to be a set of 2048^2 aliases

Do you mean a wordlist of 2048^2 words, over 4 million? That sounds impossible unless I'm missing something.

**Comment by hatmer** [comment]
new PR at #1703 that uses math to index into a 4million+ wordlist. Using a larger hardcoded wordlist was indeed impossible.

**Pull request closed without merging**
